// Copyright 2026 The Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Generated by tool/loader.dart
// ignore_for_file: non_constant_identifier_names,unused_import

import 'package:betto_mediatype_detector/betto_mediatype_detector.dart';
import 'package:betto_common/string.dart';
import 'package:meta/meta.dart';

@internal
final Registry mimeinfoDbMultipart = {
  'multipart/related': [
    RegistryEntry(
      mediaType: 'multipart/related',
      acronym: IntlString.constant('MHTML'),
      subclassOf: ['message/rfc822'],
      alias: ['application/x-mimearchive', 'message/rfc2557'],
      globs: [
        Glob(pattern: '*.mht', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mhtml', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.stringignorecase,
              offset: '0',
              value: 'From: <Saved by Windows Internet Explorer 8>',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.stringignorecase,
              offset: '0',
              value: 'From: "Saved by Internet Explorer 11"',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'MIME-Version: 1.0',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '16:512',
                  value: '\nContent-Type: multipart/related',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'multipart/alternative': [
    RegistryEntry(
      mediaType: 'multipart/alternative',
      subclassOf: [],
      alias: [],
    ),
  ],
  'multipart/appledouble': [
    RegistryEntry(
      mediaType: 'multipart/appledouble',
      subclassOf: [],
      alias: [],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '0x00051607',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'multipart/byteranges': [
    RegistryEntry(mediaType: 'multipart/byteranges', subclassOf: [], alias: []),
  ],
  'multipart/digest': [
    RegistryEntry(mediaType: 'multipart/digest', subclassOf: [], alias: []),
  ],
  'multipart/encrypted': [
    RegistryEntry(mediaType: 'multipart/encrypted', subclassOf: [], alias: []),
  ],
  'multipart/example': [
    RegistryEntry(mediaType: 'multipart/example', subclassOf: [], alias: []),
  ],
  'multipart/form-data': [
    RegistryEntry(mediaType: 'multipart/form-data', subclassOf: [], alias: []),
  ],
  'multipart/header-set': [
    RegistryEntry(mediaType: 'multipart/header-set', subclassOf: [], alias: []),
  ],
  'multipart/mixed': [
    RegistryEntry(mediaType: 'multipart/mixed', subclassOf: [], alias: []),
  ],
  'multipart/parallel': [
    RegistryEntry(mediaType: 'multipart/parallel', subclassOf: [], alias: []),
  ],
  'multipart/report': [
    RegistryEntry(mediaType: 'multipart/report', subclassOf: [], alias: []),
  ],
  'multipart/signed': [
    RegistryEntry(mediaType: 'multipart/signed', subclassOf: [], alias: []),
  ],
  'multipart/voice-message': [
    RegistryEntry(
      mediaType: 'multipart/voice-message',
      subclassOf: [],
      alias: [],
    ),
  ],
};
