// Copyright 2026 The Authors
//
// Please refer to the AUTHORS file in the base directory for this project.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Generated by tool/loader.dart
// ignore_for_file: non_constant_identifier_names,unused_import

import 'package:betto_mediatype_detector/betto_mediatype_detector.dart';
import 'package:betto_common/string.dart';
import 'package:meta/meta.dart';

@internal
final Registry mimeinfoDbX_conference = {
  'x-conference/x-cooltalk': [
    RegistryEntry(
      mediaType: 'x-conference/x-cooltalk',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.ice', weight: 50, caseSensitive: false)],
    ),
  ],
};
