// Copyright 2026 The Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Generated by tool/tika.dart

import 'package:meta/meta.dart';
import 'package:betto_mediatype_detector/betto_mediatype_detector.dart';

import 'mimeinfo_application.dart';
import 'mimeinfo_text.dart';
import 'mimeinfo_image.dart';
import 'mimeinfo_message.dart';
import 'mimeinfo_audio.dart';
import 'mimeinfo_chemical.dart';
import 'mimeinfo_multipart.dart';
import 'mimeinfo_model.dart';
import 'mimeinfo_video.dart';
import 'mimeinfo_x_conference.dart';

@internal
final Registry mimeinfoDb = {
  ...mimeinfoDbApplication,
  ...mimeinfoDbText,
  ...mimeinfoDbImage,
  ...mimeinfoDbMessage,
  ...mimeinfoDbAudio,
  ...mimeinfoDbChemical,
  ...mimeinfoDbMultipart,
  ...mimeinfoDbModel,
  ...mimeinfoDbVideo,
  ...mimeinfoDbX_conference,
};
