// Copyright 2026 The Authors
//
// Please refer to the AUTHORS file in the base directory for this project.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Generated by tool/loader.dart
// ignore_for_file: non_constant_identifier_names,unused_import

import 'package:betto_mediatype_detector/betto_mediatype_detector.dart';
import 'package:betto_common/string.dart';
import 'package:meta/meta.dart';

@internal
final Registry mimeinfoDbMessage = {
  'message/x-emlx': [
    RegistryEntry(
      mediaType: 'message/x-emlx',
      subclassOf: ['text/x-tika-text-based-message'],
      alias: [],
      globs: [Glob(pattern: '*.emlx', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 70,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '2:9',
              value: '\nRelay-Version:',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '2:9',
              value: '\n#!\\ rnews',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '2:9',
              value: '\nN#!\\ rnews',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '2:9',
              value: '\nForward\\ to',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '2:9',
              value: '\nPipe\\ to',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '2:9',
              value: '\nReturn-Path:',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '2:9',
              value: '\nFrom:',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '2:9',
              value: '\nReceived:',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '2:9',
              value: '\nMessage-ID:',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '2:9',
              value: '\nDate:',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'message/cpim': [
    RegistryEntry(mediaType: 'message/cpim', subclassOf: [], alias: []),
  ],
  'message/delivery-status': [
    RegistryEntry(
      mediaType: 'message/delivery-status',
      subclassOf: [],
      alias: [],
    ),
  ],
  'message/disposition-notification': [
    RegistryEntry(
      mediaType: 'message/disposition-notification',
      subclassOf: [],
      alias: [],
    ),
  ],
  'message/example': [
    RegistryEntry(mediaType: 'message/example', subclassOf: [], alias: []),
  ],
  'message/external-body': [
    RegistryEntry(
      mediaType: 'message/external-body',
      subclassOf: [],
      alias: [],
    ),
  ],
  'message/global': [
    RegistryEntry(mediaType: 'message/global', subclassOf: [], alias: []),
  ],
  'message/global-delivery-status': [
    RegistryEntry(
      mediaType: 'message/global-delivery-status',
      subclassOf: [],
      alias: [],
    ),
  ],
  'message/global-disposition-notification': [
    RegistryEntry(
      mediaType: 'message/global-disposition-notification',
      subclassOf: [],
      alias: [],
    ),
  ],
  'message/global-headers': [
    RegistryEntry(
      mediaType: 'message/global-headers',
      subclassOf: [],
      alias: [],
    ),
  ],
  'message/http': [
    RegistryEntry(mediaType: 'message/http', subclassOf: [], alias: []),
  ],
  'message/imdn+xml': [
    RegistryEntry(mediaType: 'message/imdn+xml', subclassOf: [], alias: []),
  ],
  'message/news': [
    RegistryEntry(
      mediaType: 'message/news',
      subclassOf: ['text/x-tika-text-based-message'],
      alias: [],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'Path:',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'Xref:',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'Article',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'message/partial': [
    RegistryEntry(mediaType: 'message/partial', subclassOf: [], alias: []),
  ],
  'message/rfc822': [
    RegistryEntry(
      mediaType: 'message/rfc822',
      subclassOf: ['text/x-tika-text-based-message'],
      alias: [],
      globs: [
        Glob(pattern: '*.eml', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mime', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.stringignorecase,
              offset: '0',
              value: 'Relay-Version:',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#!\\ rnews',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'N#!\\ rnews',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'Forward\\ to',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'Pipe\\ to',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.stringignorecase,
              offset: '0',
              value: 'Return-Path:',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.stringignorecase,
              offset: '0',
              value: 'Message-ID:',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'X-Mailer:',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'X-Notes-Item:',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '0:8192',
                  value: 'Message-ID:',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
            Match.factory(
              type: MatchType.regex,
              offset: '0',
              value: '(X|DKIM|ARC)-',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.stringignorecase,
                  offset: '0:8192',
                  value: '\nDate:',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '0:8192',
                  value: '\nDelivered-To:',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.stringignorecase,
                  offset: '0:8192',
                  value: '\nFrom:',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.stringignorecase,
                  offset: '0:8192',
                  value: '\nMessage-ID:',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.stringignorecase,
                  offset: '0:8192',
                  value: '\nMIME-Version:',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.stringignorecase,
                  offset: '0:8192',
                  value: '\nReceived:',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.stringignorecase,
                  offset: '0:8192',
                  value: '\nRelay-Version:',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.stringignorecase,
                  offset: '0:8192',
                  value: '\nReturn-Path:',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '0:8192',
                  value: '\nStatus:',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '0:8192',
                  value: '\nUser-Agent:',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '0:8192',
                  value: '\nX-Mailer:',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.stringignorecase,
                  offset: '0:8192',
                  value: '\nX-Originating-IP:',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
        Magic(
          priority: 45,
          matches: [
            Match.factory(
              type: MatchType.byte,
              offset: '0',
              value: null,
              mask: null,
              minShouldMatch: 2,
              subMatches: [
                Match.factory(
                  type: MatchType.byte,
                  offset: '0',
                  value: null,
                  mask: null,
                  minShouldMatch: 1,
                  subMatches: [
                    Match.factory(
                      type: MatchType.stringignorecase,
                      offset: '0',
                      value: 'Content-ID:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.stringignorecase,
                      offset: '0',
                      value: 'Content-Location:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.stringignorecase,
                      offset: '0',
                      value: 'Content-Transfer-Encoding:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.stringignorecase,
                      offset: '0',
                      value: 'Content-Type:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.stringignorecase,
                      offset: '0',
                      value: 'Date:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.string,
                      offset: '0',
                      value: 'Delivered-To:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.stringignorecase,
                      offset: '0',
                      value: 'From:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.stringignorecase,
                      offset: '0',
                      value: 'Message-ID:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.stringignorecase,
                      offset: '0',
                      value: 'MIME-Version:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.stringignorecase,
                      offset: '0',
                      value: 'Received:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.stringignorecase,
                      offset: '0',
                      value: 'Relay-Version:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.stringignorecase,
                      offset: '0',
                      value: 'Return-Path:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.string,
                      offset: '0',
                      value: 'Sent:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.string,
                      offset: '0',
                      value: 'Status:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.string,
                      offset: '0',
                      value: 'Subject:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.string,
                      offset: '0',
                      value: 'To:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.string,
                      offset: '0',
                      value: 'User-Agent:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.string,
                      offset: '0',
                      value: 'X-Mailer:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.stringignorecase,
                      offset: '0',
                      value: 'X-Originating-IP:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.string,
                      offset: '0',
                      value: '0xefbbbf',
                      mask: null,
                      minShouldMatch: null,
                      subMatches: [
                        Match.factory(
                          type: MatchType.stringignorecase,
                          offset: '3',
                          value: 'Content-ID:',
                          mask: null,
                          minShouldMatch: null,
                        ),
                        Match.factory(
                          type: MatchType.stringignorecase,
                          offset: '3',
                          value: 'Content-Location:',
                          mask: null,
                          minShouldMatch: null,
                        ),
                        Match.factory(
                          type: MatchType.stringignorecase,
                          offset: '3',
                          value: 'Content-Transfer-Encoding:',
                          mask: null,
                          minShouldMatch: null,
                        ),
                        Match.factory(
                          type: MatchType.stringignorecase,
                          offset: '3',
                          value: 'Content-Type:',
                          mask: null,
                          minShouldMatch: null,
                        ),
                        Match.factory(
                          type: MatchType.stringignorecase,
                          offset: '3',
                          value: 'Date:',
                          mask: null,
                          minShouldMatch: null,
                        ),
                        Match.factory(
                          type: MatchType.string,
                          offset: '3',
                          value: 'Delivered-To:',
                          mask: null,
                          minShouldMatch: null,
                        ),
                        Match.factory(
                          type: MatchType.stringignorecase,
                          offset: '3',
                          value: 'From:',
                          mask: null,
                          minShouldMatch: null,
                        ),
                        Match.factory(
                          type: MatchType.stringignorecase,
                          offset: '3',
                          value: 'Message-ID:',
                          mask: null,
                          minShouldMatch: null,
                        ),
                        Match.factory(
                          type: MatchType.stringignorecase,
                          offset: '3',
                          value: 'MIME-Version:',
                          mask: null,
                          minShouldMatch: null,
                        ),
                        Match.factory(
                          type: MatchType.stringignorecase,
                          offset: '3',
                          value: 'Received:',
                          mask: null,
                          minShouldMatch: null,
                        ),
                        Match.factory(
                          type: MatchType.stringignorecase,
                          offset: '3',
                          value: 'Relay-Version:',
                          mask: null,
                          minShouldMatch: null,
                        ),
                        Match.factory(
                          type: MatchType.stringignorecase,
                          offset: '3',
                          value: 'Return-Path:',
                          mask: null,
                          minShouldMatch: null,
                        ),
                        Match.factory(
                          type: MatchType.string,
                          offset: '3',
                          value: 'Sent:',
                          mask: null,
                          minShouldMatch: null,
                        ),
                        Match.factory(
                          type: MatchType.string,
                          offset: '3',
                          value: 'Status:',
                          mask: null,
                          minShouldMatch: null,
                        ),
                        Match.factory(
                          type: MatchType.string,
                          offset: '3',
                          value: 'Subject:',
                          mask: null,
                          minShouldMatch: null,
                        ),
                        Match.factory(
                          type: MatchType.string,
                          offset: '3',
                          value: 'To:',
                          mask: null,
                          minShouldMatch: null,
                        ),
                        Match.factory(
                          type: MatchType.string,
                          offset: '3',
                          value: 'User-Agent:',
                          mask: null,
                          minShouldMatch: null,
                        ),
                        Match.factory(
                          type: MatchType.string,
                          offset: '3',
                          value: 'X-Mailer:',
                          mask: null,
                          minShouldMatch: null,
                        ),
                        Match.factory(
                          type: MatchType.stringignorecase,
                          offset: '3',
                          value: 'X-Originating-IP:',
                          mask: null,
                          minShouldMatch: null,
                        ),
                      ],
                    ),
                  ],
                ),
                Match.factory(
                  type: MatchType.byte,
                  offset: '0',
                  value: null,
                  mask: null,
                  minShouldMatch: 1,
                  subMatches: [
                    Match.factory(
                      type: MatchType.stringignorecase,
                      offset: '0:1024',
                      value: '\nContent-ID:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.stringignorecase,
                      offset: '0:1024',
                      value: '\nContent-Location:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.stringignorecase,
                      offset: '0:1024',
                      value: '\nContent-Transfer-Encoding:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.stringignorecase,
                      offset: '0:1024',
                      value: '\nContent-Type:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.stringignorecase,
                      offset: '0:1024',
                      value: '\nDate:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.string,
                      offset: '0:1024',
                      value: '\nDelivered-To:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.stringignorecase,
                      offset: '0:1024',
                      value: '\nFrom:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.stringignorecase,
                      offset: '0:1024',
                      value: '\nMIME-Version:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.stringignorecase,
                      offset: '0:1024',
                      value: '\nReceived:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.stringignorecase,
                      offset: '0:1024',
                      value: '\nRelay-Version:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.stringignorecase,
                      offset: '0:1024',
                      value: '\nReturn-Path:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.string,
                      offset: '0:1024',
                      value: '\nSent:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.string,
                      offset: '0:1024',
                      value: '\nStatus:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.string,
                      offset: '0:1024',
                      value: '\nSubject:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.string,
                      offset: '0:1024',
                      value: '\nTo:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.string,
                      offset: '0:1024',
                      value: '\nUser-Agent:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.string,
                      offset: '0:1024',
                      value: '\nX-Mailer:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.stringignorecase,
                      offset: '0:1024',
                      value: '\nX-Originating-IP:',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.string,
                      offset: '0:1024',
                      value: '\nDKIM-',
                      mask: null,
                      minShouldMatch: null,
                    ),
                    Match.factory(
                      type: MatchType.string,
                      offset: '0:1024',
                      value: '\nARC-',
                      mask: null,
                      minShouldMatch: null,
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
        Magic(
          priority: 40,
          matches: [
            Match.factory(
              type: MatchType.stringignorecase,
              offset: '0:1000',
              value: '\nMessage-ID:',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'message/s-http': [
    RegistryEntry(mediaType: 'message/s-http', subclassOf: [], alias: []),
  ],
  'message/sip': [
    RegistryEntry(mediaType: 'message/sip', subclassOf: [], alias: []),
  ],
  'message/sipfrag': [
    RegistryEntry(mediaType: 'message/sipfrag', subclassOf: [], alias: []),
  ],
  'message/tracking-status': [
    RegistryEntry(
      mediaType: 'message/tracking-status',
      subclassOf: [],
      alias: [],
    ),
  ],
  'message/vnd.si.simp': [
    RegistryEntry(mediaType: 'message/vnd.si.simp', subclassOf: [], alias: []),
  ],
};
