// Copyright 2026 The Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Generated by tool/loader.dart
// ignore_for_file: non_constant_identifier_names,unused_import

import 'package:betto_mediatype_detector/betto_mediatype_detector.dart';
import 'package:betto_common/string.dart';
import 'package:meta/meta.dart';

@internal
final Registry mimeinfoDbVideo = {
  'video/3gpp': [
    RegistryEntry(
      mediaType: 'video/3gpp',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.3gp', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftyp3ge6',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftyp3ge7',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftyp3gg6',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftyp3gp1',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftyp3gp2',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftyp3gp3',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftyp3gp4',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftyp3gp5',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftyp3gp6',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftyp3gs7',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/3gpp-tt': [
    RegistryEntry(mediaType: 'video/3gpp-tt', subclassOf: [], alias: []),
  ],
  'video/3gpp2': [
    RegistryEntry(
      mediaType: 'video/3gpp2',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.3g2', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftyp3g2a',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftyp3g2b',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftyp3g2c',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/bmpeg': [
    RegistryEntry(mediaType: 'video/bmpeg', subclassOf: [], alias: []),
  ],
  'video/bt656': [
    RegistryEntry(mediaType: 'video/bt656', subclassOf: [], alias: []),
  ],
  'video/celb': [
    RegistryEntry(mediaType: 'video/celb', subclassOf: [], alias: []),
  ],
  'video/dv': [RegistryEntry(mediaType: 'video/dv', subclassOf: [], alias: [])],
  'video/example': [
    RegistryEntry(mediaType: 'video/example', subclassOf: [], alias: []),
  ],
  'video/h261': [
    RegistryEntry(
      mediaType: 'video/h261',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.h261', weight: 50, caseSensitive: false)],
    ),
  ],
  'video/h263': [
    RegistryEntry(
      mediaType: 'video/h263',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.h263', weight: 50, caseSensitive: false)],
    ),
  ],
  'video/h263-1998': [
    RegistryEntry(mediaType: 'video/h263-1998', subclassOf: [], alias: []),
  ],
  'video/h263-2000': [
    RegistryEntry(mediaType: 'video/h263-2000', subclassOf: [], alias: []),
  ],
  'video/h264': [
    RegistryEntry(
      mediaType: 'video/h264',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.h264', weight: 50, caseSensitive: false)],
    ),
  ],
  'video/iso.segment': [
    RegistryEntry(
      mediaType: 'video/iso.segment',
      subclassOf: ['video/quicktime'],
      alias: [],
      globs: [Glob(pattern: '*.m4s', weight: 50, caseSensitive: false)],
    ),
  ],
  'video/jpeg': [
    RegistryEntry(
      mediaType: 'video/jpeg',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.jpgv', weight: 50, caseSensitive: false)],
    ),
  ],
  'video/jpeg2000': [
    RegistryEntry(mediaType: 'video/jpeg2000', subclassOf: [], alias: []),
  ],
  'video/mj2': [
    RegistryEntry(
      mediaType: 'video/mj2',
      acronym: IntlString.constant('MJ2'),
      subclassOf: ['image/x-jp2-container'],
      alias: [],
      globs: [
        Glob(pattern: '*.mj2', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mjp2', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '0x0000000C6A5020200D0A870A',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '20',
                  value: '0x6d6a7032',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'video/mp1s': [
    RegistryEntry(mediaType: 'video/mp1s', subclassOf: [], alias: []),
  ],
  'video/mp2p': [
    RegistryEntry(mediaType: 'video/mp2p', subclassOf: [], alias: []),
  ],
  'video/mp2t': [
    RegistryEntry(mediaType: 'video/mp2t', subclassOf: [], alias: []),
  ],
  'video/mp4': [
    RegistryEntry(
      mediaType: 'video/mp4',
      subclassOf: ['video/quicktime'],
      alias: [],
      globs: [
        Glob(pattern: '*.mp4', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mp4v', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mpg4', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftypmp41',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftypmp42',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/mp4v-es': [
    RegistryEntry(mediaType: 'video/mp4v-es', subclassOf: [], alias: []),
  ],
  'video/mpeg': [
    RegistryEntry(
      mediaType: 'video/mpeg',
      subclassOf: [],
      alias: [],
      globs: [
        Glob(pattern: '*.mpeg', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mpg', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mpe', weight: 50, caseSensitive: false),
        Glob(pattern: '*.m1v', weight: 50, caseSensitive: false),
        Glob(pattern: '*.m2v', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '\x00\x00\x01\xb3',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '\x00\x00\x01\xba',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/mpeg4-generic': [
    RegistryEntry(mediaType: 'video/mpeg4-generic', subclassOf: [], alias: []),
  ],
  'video/mpv': [
    RegistryEntry(mediaType: 'video/mpv', subclassOf: [], alias: []),
  ],
  'video/nv': [RegistryEntry(mediaType: 'video/nv', subclassOf: [], alias: [])],
  'video/ogg': [
    RegistryEntry(
      mediaType: 'video/ogg',
      subclassOf: ['application/ogg'],
      alias: [],
      globs: [Glob(pattern: '*.ogv', weight: 50, caseSensitive: false)],
    ),
  ],
  'video/daala': [
    RegistryEntry(
      mediaType: 'video/daala',
      subclassOf: ['video/ogg'],
      alias: ['video/x-daala'],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'OggS\x00.......................\x80daala',
              mask:
                  '0xFFFFFFFF00000000000000000000000000000000000000000000000000FFFFFFFFFFFF',
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/theora': [
    RegistryEntry(
      mediaType: 'video/theora',
      subclassOf: ['video/ogg'],
      alias: ['video/x-theora'],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'OggS\x00.......................\x80theora',
              mask:
                  '0xFFFFFFFF00000000000000000000000000000000000000000000000000FFFFFFFFFFFFFF',
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/x-dirac': [
    RegistryEntry(
      mediaType: 'video/x-dirac',
      subclassOf: ['video/ogg'],
      alias: [],
      globs: [Glob(pattern: '*.drc', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'OggS\x00.......................BBCD',
              mask:
                  '0xFFFFFFFF00000000000000000000000000000000000000000000000000FFFFFFFF',
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/x-ogm': [
    RegistryEntry(
      mediaType: 'video/x-ogm',
      subclassOf: ['video/ogg'],
      alias: [],
      globs: [Glob(pattern: '*.ogm', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'OggS\x00.......................video',
              mask:
                  '0xFFFFFFFF00000000000000000000000000000000000000000000000000FFFFFFFFFF',
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/x-ogguvs': [
    RegistryEntry(
      mediaType: 'video/x-ogguvs',
      subclassOf: ['video/ogg'],
      alias: ['video/x-ogg-uvs'],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'OggS\x00.......................UVS ',
              mask:
                  '0xFFFFFFFF00000000000000000000000000000000000000000000000000FFFFFFFF',
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/x-oggyuv': [
    RegistryEntry(
      mediaType: 'video/x-oggyuv',
      subclassOf: ['video/ogg'],
      alias: ['video/x-ogg-yuv'],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'OggS\x00.......................\x01YUV',
              mask:
                  '0xFFFFFFFF00000000000000000000000000000000000000000000000000FFFFFFFF',
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/x-oggrgb': [
    RegistryEntry(
      mediaType: 'video/x-oggrgb',
      subclassOf: ['video/ogg'],
      alias: ['video/x-ogg-rgb'],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'OggS\x00.......................\x01RGB',
              mask:
                  '0xFFFFFFFF00000000000000000000000000000000000000000000000000FFFFFFFF',
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/parityfec': [
    RegistryEntry(mediaType: 'video/parityfec', subclassOf: [], alias: []),
  ],
  'video/pointer': [
    RegistryEntry(mediaType: 'video/pointer', subclassOf: [], alias: []),
  ],
  'video/quicktime': [
    RegistryEntry(
      mediaType: 'video/quicktime',
      subclassOf: ['application/quicktime'],
      alias: [],
      globs: [
        Glob(pattern: '*.qt', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mov', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'moov\x00',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'mdat\x00',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'free\x00',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'skip\x00',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'pnot\x00',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftyp',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '\x00\x00\x00\bwide',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/raw': [
    RegistryEntry(mediaType: 'video/raw', subclassOf: [], alias: []),
  ],
  'video/rtp-enc-aescm128': [
    RegistryEntry(
      mediaType: 'video/rtp-enc-aescm128',
      subclassOf: [],
      alias: [],
    ),
  ],
  'video/rtx': [
    RegistryEntry(mediaType: 'video/rtx', subclassOf: [], alias: []),
  ],
  'video/smpte292m': [
    RegistryEntry(mediaType: 'video/smpte292m', subclassOf: [], alias: []),
  ],
  'video/ulpfec': [
    RegistryEntry(mediaType: 'video/ulpfec', subclassOf: [], alias: []),
  ],
  'video/vc1': [
    RegistryEntry(mediaType: 'video/vc1', subclassOf: [], alias: []),
  ],
  'video/vnd.cctv': [
    RegistryEntry(mediaType: 'video/vnd.cctv', subclassOf: [], alias: []),
  ],
  'video/vnd.dlna.mpeg-tts': [
    RegistryEntry(
      mediaType: 'video/vnd.dlna.mpeg-tts',
      subclassOf: [],
      alias: [],
    ),
  ],
  'video/vnd.fvt': [
    RegistryEntry(
      mediaType: 'video/vnd.fvt',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.fvt', weight: 50, caseSensitive: false)],
    ),
  ],
  'video/vnd.hns.video': [
    RegistryEntry(mediaType: 'video/vnd.hns.video', subclassOf: [], alias: []),
  ],
  'video/vnd.iptvforum.1dparityfec-1010': [
    RegistryEntry(
      mediaType: 'video/vnd.iptvforum.1dparityfec-1010',
      subclassOf: [],
      alias: [],
    ),
  ],
  'video/vnd.iptvforum.1dparityfec-2005': [
    RegistryEntry(
      mediaType: 'video/vnd.iptvforum.1dparityfec-2005',
      subclassOf: [],
      alias: [],
    ),
  ],
  'video/vnd.iptvforum.2dparityfec-1010': [
    RegistryEntry(
      mediaType: 'video/vnd.iptvforum.2dparityfec-1010',
      subclassOf: [],
      alias: [],
    ),
  ],
  'video/vnd.iptvforum.2dparityfec-2005': [
    RegistryEntry(
      mediaType: 'video/vnd.iptvforum.2dparityfec-2005',
      subclassOf: [],
      alias: [],
    ),
  ],
  'video/vnd.iptvforum.ttsavc': [
    RegistryEntry(
      mediaType: 'video/vnd.iptvforum.ttsavc',
      subclassOf: [],
      alias: [],
    ),
  ],
  'video/vnd.iptvforum.ttsmpeg2': [
    RegistryEntry(
      mediaType: 'video/vnd.iptvforum.ttsmpeg2',
      subclassOf: [],
      alias: [],
    ),
  ],
  'video/vnd.motorola.video': [
    RegistryEntry(
      mediaType: 'video/vnd.motorola.video',
      subclassOf: [],
      alias: [],
    ),
  ],
  'video/vnd.motorola.videop': [
    RegistryEntry(
      mediaType: 'video/vnd.motorola.videop',
      subclassOf: [],
      alias: [],
    ),
  ],
  'video/vnd.mpegurl': [
    RegistryEntry(
      mediaType: 'video/vnd.mpegurl',
      subclassOf: [],
      alias: [],
      globs: [
        Glob(pattern: '*.mxu', weight: 50, caseSensitive: false),
        Glob(pattern: '*.m4u', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'video/vnd.ms-playready.media.pyv': [
    RegistryEntry(
      mediaType: 'video/vnd.ms-playready.media.pyv',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.pyv', weight: 50, caseSensitive: false)],
    ),
  ],
  'video/vnd.nokia.interleaved-multimedia': [
    RegistryEntry(
      mediaType: 'video/vnd.nokia.interleaved-multimedia',
      subclassOf: [],
      alias: [],
    ),
  ],
  'video/vnd.nokia.videovoip': [
    RegistryEntry(
      mediaType: 'video/vnd.nokia.videovoip',
      subclassOf: [],
      alias: [],
    ),
  ],
  'video/vnd.objectvideo': [
    RegistryEntry(
      mediaType: 'video/vnd.objectvideo',
      subclassOf: [],
      alias: [],
    ),
  ],
  'video/vnd.sealed.mpeg1': [
    RegistryEntry(
      mediaType: 'video/vnd.sealed.mpeg1',
      subclassOf: [],
      alias: [],
    ),
  ],
  'video/vnd.sealed.mpeg4': [
    RegistryEntry(
      mediaType: 'video/vnd.sealed.mpeg4',
      subclassOf: [],
      alias: [],
    ),
  ],
  'video/vnd.sealed.swf': [
    RegistryEntry(mediaType: 'video/vnd.sealed.swf', subclassOf: [], alias: []),
  ],
  'video/vnd.sealedmedia.softseal.mov': [
    RegistryEntry(
      mediaType: 'video/vnd.sealedmedia.softseal.mov',
      subclassOf: [],
      alias: [],
    ),
  ],
  'video/vnd.vivo': [
    RegistryEntry(
      mediaType: 'video/vnd.vivo',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.viv', weight: 50, caseSensitive: false)],
    ),
  ],
  'video/x-f4v': [
    RegistryEntry(
      mediaType: 'video/x-f4v',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.f4v', weight: 50, caseSensitive: false)],
    ),
  ],
  'video/x-flc': [
    RegistryEntry(
      mediaType: 'video/x-flc',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.flc', weight: 50, caseSensitive: false)],
    ),
  ],
  'video/x-fli': [
    RegistryEntry(
      mediaType: 'video/x-fli',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.fli', weight: 50, caseSensitive: false)],
    ),
  ],
  'video/x-flv': [
    RegistryEntry(
      mediaType: 'video/x-flv',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.flv', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'FLV',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/x-jng': [
    RegistryEntry(
      mediaType: 'video/x-jng',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.jng', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '\x8bJNG',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/x-m4v': [
    RegistryEntry(
      mediaType: 'video/x-m4v',
      subclassOf: ['video/mp4'],
      alias: [],
      globs: [Glob(pattern: '*.m4v', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftypM4V ',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftypM4VH',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftypM4VP',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/x-mng': [
    RegistryEntry(
      mediaType: 'video/x-mng',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.mng', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '\x8aMNG',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/x-ms-asf': [
    RegistryEntry(
      mediaType: 'video/x-ms-asf',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.asf', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.big32,
              offset: '0',
              value: '0x3026b275',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/x-ms-wm': [
    RegistryEntry(
      mediaType: 'video/x-ms-wm',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.wm', weight: 50, caseSensitive: false)],
    ),
  ],
  'video/x-ms-wmv': [
    RegistryEntry(
      mediaType: 'video/x-ms-wmv',
      subclassOf: ['video/x-ms-asf'],
      alias: [],
      globs: [Glob(pattern: '*.wmv', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.byte,
              offset: '0:8192',
              value: 'Windows Media Video',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.byte,
              offset: '0:8192',
              value: 'VC-1 Advanced Profile',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.byte,
              offset: '0:8192',
              value: 'wmv2',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/x-ms-wmx': [
    RegistryEntry(
      mediaType: 'video/x-ms-wmx',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.wmx', weight: 50, caseSensitive: false)],
    ),
  ],
  'video/x-ms-wvx': [
    RegistryEntry(
      mediaType: 'video/x-ms-wvx',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.wvx', weight: 50, caseSensitive: false)],
    ),
  ],
  'video/x-msvideo': [
    RegistryEntry(
      mediaType: 'video/x-msvideo',
      subclassOf: [],
      alias: ['video/avi', 'video/msvideo'],
      globs: [Glob(pattern: '*.avi', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'RIFF....AVI ',
              mask: '0xFFFFFFFF00000000FFFFFFFF',
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '8',
              value: 'AVI ',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/x-sgi-movie': [
    RegistryEntry(
      mediaType: 'video/x-sgi-movie',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.movie', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'MOVI\x00',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'MOVI\x01',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'MOVI\x02',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'MOVI\xfe',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'MOVI\xff',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/x-matroska': [
    RegistryEntry(
      mediaType: 'video/x-matroska',
      subclassOf: ['application/x-matroska'],
      alias: [],
      globs: [Glob(pattern: '*.mkv', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '0x1A45DFA3934282886D6174726F736B61',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/webm': [
    RegistryEntry(
      mediaType: 'video/webm',
      subclassOf: ['application/x-matroska'],
      alias: [],
      globs: [Glob(pattern: '*.webm', weight: 50, caseSensitive: false)],
    ),
  ],
};
