// Copyright 2026 The Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Generated by tool/loader.dart
// ignore_for_file: non_constant_identifier_names,unused_import

import 'package:betto_mediatype_detector/betto_mediatype_detector.dart';
import 'package:betto_common/string.dart';
import 'package:meta/meta.dart';

@internal
final Registry mimeinfoDbChemical = {
  'chemical/x-cdx': [
    RegistryEntry(
      mediaType: 'chemical/x-cdx',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.cdx', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'VjCD0100',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'chemical/x-cif': [
    RegistryEntry(
      mediaType: 'chemical/x-cif',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.cif', weight: 50, caseSensitive: false)],
    ),
  ],
  'chemical/x-cmdf': [
    RegistryEntry(
      mediaType: 'chemical/x-cmdf',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.cmdf', weight: 50, caseSensitive: false)],
    ),
  ],
  'chemical/x-cml': [
    RegistryEntry(
      mediaType: 'chemical/x-cml',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.cml', weight: 50, caseSensitive: false)],
    ),
  ],
  'chemical/x-csml': [
    RegistryEntry(
      mediaType: 'chemical/x-csml',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.csml', weight: 50, caseSensitive: false)],
    ),
  ],
  'chemical/x-pdb': [
    RegistryEntry(
      mediaType: 'chemical/x-pdb',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.pdb', weight: 50, caseSensitive: false)],
    ),
  ],
  'chemical/x-xyz': [
    RegistryEntry(
      mediaType: 'chemical/x-xyz',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.xyz', weight: 50, caseSensitive: false)],
    ),
  ],
};
