// Copyright 2026 The Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Generated by tool/loader.dart
// ignore_for_file: non_constant_identifier_names,unused_import

import 'package:betto_mediatype_detector/betto_mediatype_detector.dart';
import 'package:betto_common/string.dart';
import 'package:meta/meta.dart';

@internal
final Registry mimeinfoDbText = {
  'text/iso19139+xml': [
    RegistryEntry(
      mediaType: 'text/iso19139+xml',
      subclassOf: ['application/xml'],
      alias: [],
      globs: [Glob(pattern: '*.iso19139', weight: 50, caseSensitive: false)],
      rootXML: [
        RootXML(namespaceURI: null, localName: 'MD_metadata'),
        RootXML(
          namespaceURI: 'http://www.isotc211.org/2005/gmd',
          localName: 'MD_metadata',
        ),
      ],
    ),
  ],
  'text/javascript': [
    RegistryEntry(
      mediaType: 'text/javascript',
      subclassOf: ['text/plain'],
      alias: ['application/javascript', 'application/x-javascript'],
      globs: [
        Glob(pattern: '*.js', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mjs', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '/* jQuery ',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '/*! jQuery ',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '/*!',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.byte,
                  offset: '4:8',
                  value: '* jQuery ',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '(function(e,undefined){',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '!function(window,undefined){',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '/*  Prototype JavaScript ',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'var Prototype={',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'function \$w(t){',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '/** @license React',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '/**',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.byte,
                  offset: '4:8',
                  value: '* React ',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'text/x-robots': [
    RegistryEntry(
      mediaType: 'text/x-robots',
      subclassOf: ['text/plain'],
      alias: [],
      magic: [
        Magic(
          priority: 55,
          matches: [
            Match.factory(
              type: MatchType.byte,
              offset: '0',
              value: null,
              mask: null,
              minShouldMatch: 2,
              subMatches: [
                Match.factory(
                  type: MatchType.stringignorecase,
                  offset: '0',
                  value: 'user-agent:',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.stringignorecase,
                  offset: '0',
                  value: 'allow:',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.stringignorecase,
                  offset: '0',
                  value: 'disallow:',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.stringignorecase,
                  offset: '0',
                  value: 'sitemap:',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.stringignorecase,
                  offset: '0:1000',
                  value: '\nuser-agent:',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.stringignorecase,
                  offset: '0:1000',
                  value: '\nallow:',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.stringignorecase,
                  offset: '0:1000',
                  value: '\ndisallow:',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.stringignorecase,
                  offset: '0:1000',
                  value: '\nsitemap:',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'text/x-actionscript': [
    RegistryEntry(
      mediaType: 'text/x-actionscript',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.as', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-ada': [
    RegistryEntry(
      mediaType: 'text/x-ada',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: '*.ada', weight: 50, caseSensitive: false),
        Glob(pattern: '*.adb', weight: 50, caseSensitive: false),
        Glob(pattern: '*.ads', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'text/x-applescript': [
    RegistryEntry(
      mediaType: 'text/x-applescript',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.applescript', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/asp': [
    RegistryEntry(
      mediaType: 'text/asp',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.asp', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/aspdotnet': [
    RegistryEntry(
      mediaType: 'text/aspdotnet',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.aspx', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-aspectj': [
    RegistryEntry(
      mediaType: 'text/x-aspectj',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.aj', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-assembly': [
    RegistryEntry(
      mediaType: 'text/x-assembly',
      subclassOf: ['text/plain'],
      alias: ['text/x-asm'],
      globs: [
        Glob(pattern: '*.s', weight: 50, caseSensitive: false),
        Glob(pattern: '*.S', weight: 50, caseSensitive: false),
        Glob(pattern: '*.asm', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'text/calendar': [
    RegistryEntry(
      mediaType: 'text/calendar',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: '*.ics', weight: 50, caseSensitive: false),
        Glob(pattern: '*.ifb', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'BEGIN:VCALENDAR',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '15:360',
                  value: '\nVERSION:2.0',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'text/x-config': [
    RegistryEntry(
      mediaType: 'text/x-config',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: '*.config', weight: 50, caseSensitive: false),
        Glob(pattern: '*.conf', weight: 50, caseSensitive: false),
        Glob(pattern: '*.cfg', weight: 50, caseSensitive: false),
        Glob(pattern: '*.xconf', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'text/css': [
    RegistryEntry(
      mediaType: 'text/css',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.css', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/csv': [
    RegistryEntry(
      mediaType: 'text/csv',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.csv', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/directory': [
    RegistryEntry(mediaType: 'text/directory', subclassOf: [], alias: []),
  ],
  'text/dns': [RegistryEntry(mediaType: 'text/dns', subclassOf: [], alias: [])],
  'text/ecmascript': [
    RegistryEntry(mediaType: 'text/ecmascript', subclassOf: [], alias: []),
  ],
  'text/enriched': [
    RegistryEntry(mediaType: 'text/enriched', subclassOf: [], alias: []),
  ],
  'text/example': [
    RegistryEntry(mediaType: 'text/example', subclassOf: [], alias: []),
  ],
  'text/html': [
    RegistryEntry(
      mediaType: 'text/html',
      acronym: IntlString.constant('HTML'),
      subclassOf: [],
      alias: [],
      globs: [
        Glob(pattern: '*.html', weight: 50, caseSensitive: false),
        Glob(pattern: '*.htm', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.regex,
              offset: '0',
              value: '(?i)<(html|head|body|title|div)[ >]',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.regex,
              offset: '0',
              value: '(?i)<h[123][ >]',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
        Magic(
          priority: 40,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0:64',
              value: '<!DOCTYPE HTML',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0:64',
              value: '<!DOCTYPE html',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0:64',
              value: '<!doctype HTML',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0:64',
              value: '<!doctype html',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0:64',
              value: '<HEAD',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0:64',
              value: '<head',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0:64',
              value: '<TITLE',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0:64',
              value: '<title',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0:64',
              value: '<HTML',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0:128',
              value: '<html',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
        Magic(
          priority: 20,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '128:8192',
              value: '<html',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
      rootXML: [
        RootXML(namespaceURI: null, localName: 'html'),
        RootXML(namespaceURI: null, localName: 'HTML'),
        RootXML(namespaceURI: null, localName: 'link'),
        RootXML(namespaceURI: null, localName: 'LINK'),
        RootXML(namespaceURI: null, localName: 'body'),
        RootXML(namespaceURI: null, localName: 'BODY'),
        RootXML(namespaceURI: null, localName: 'p'),
        RootXML(namespaceURI: null, localName: 'P'),
        RootXML(namespaceURI: null, localName: 'script'),
        RootXML(namespaceURI: null, localName: 'SCRIPT'),
        RootXML(namespaceURI: null, localName: 'frameset'),
        RootXML(namespaceURI: null, localName: 'FRAMESET'),
        RootXML(namespaceURI: null, localName: 'iframe'),
        RootXML(namespaceURI: null, localName: 'IFRAME'),
      ],
    ),
  ],
  'text/x-makefile': [
    RegistryEntry(
      mediaType: 'text/x-makefile',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: 'Makefile', weight: 50, caseSensitive: true),
        Glob(pattern: 'GNUMakefile', weight: 50, caseSensitive: true),
      ],
      magic: [
        Magic(
          priority: 20,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '# Makefile.in generated by',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#!make',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#!/usr/bin/make',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#!/usr/local/bin/make',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#!/usr/bin/env make',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'text/parityfec': [
    RegistryEntry(mediaType: 'text/parityfec', subclassOf: [], alias: []),
  ],
  'text/plain': [
    RegistryEntry(
      mediaType: 'text/plain',
      subclassOf: [],
      alias: [],
      globs: [
        Glob(pattern: '*.txt', weight: 50, caseSensitive: false),
        Glob(pattern: '*.text', weight: 50, caseSensitive: false),
        Glob(pattern: '*.def', weight: 50, caseSensitive: false),
        Glob(pattern: '*.list', weight: 50, caseSensitive: false),
        Glob(pattern: '*.in', weight: 50, caseSensitive: false),
        Glob(pattern: 'INSTALL', weight: 50, caseSensitive: true),
        Glob(pattern: 'KEYS', weight: 50, caseSensitive: true),
        Glob(pattern: 'LICENSE', weight: 50, caseSensitive: true),
        Glob(pattern: 'NOTICE', weight: 50, caseSensitive: true),
        Glob(pattern: 'README', weight: 50, caseSensitive: true),
        Glob(pattern: 'abs-linkmap', weight: 50, caseSensitive: true),
        Glob(pattern: 'abs-menulinks', weight: 50, caseSensitive: true),
        Glob(pattern: '*.aart', weight: 50, caseSensitive: false),
        Glob(pattern: '*.ac', weight: 50, caseSensitive: false),
        Glob(pattern: '*.am', weight: 50, caseSensitive: false),
        Glob(pattern: '*.apt', weight: 50, caseSensitive: false),
        Glob(pattern: '*.bsh', weight: 50, caseSensitive: false),
        Glob(pattern: '*.classpath', weight: 50, caseSensitive: false),
        Glob(pattern: '*.cnd', weight: 50, caseSensitive: false),
        Glob(pattern: '*.cwiki', weight: 50, caseSensitive: false),
        Glob(pattern: '*.data', weight: 50, caseSensitive: false),
        Glob(pattern: '*.dcl', weight: 50, caseSensitive: false),
        Glob(pattern: '*.dsp', weight: 50, caseSensitive: false),
        Glob(pattern: '*.dsw', weight: 50, caseSensitive: false),
        Glob(pattern: '*.egrm', weight: 50, caseSensitive: false),
        Glob(pattern: '*.ent', weight: 50, caseSensitive: false),
        Glob(pattern: '*.ft', weight: 50, caseSensitive: false),
        Glob(pattern: '*.fn', weight: 50, caseSensitive: false),
        Glob(pattern: '*.fv', weight: 50, caseSensitive: false),
        Glob(pattern: '*.grm', weight: 50, caseSensitive: false),
        Glob(pattern: '*.g', weight: 50, caseSensitive: false),
        Glob(pattern: '.htaccess', weight: 50, caseSensitive: true),
        Glob(pattern: '*.handlers', weight: 50, caseSensitive: false),
        Glob(pattern: '*.htc', weight: 50, caseSensitive: false),
        Glob(pattern: '*.ihtml', weight: 50, caseSensitive: false),
        Glob(pattern: '*.jmx', weight: 50, caseSensitive: false),
        Glob(pattern: '*.junit', weight: 50, caseSensitive: false),
        Glob(pattern: '*.jx', weight: 50, caseSensitive: false),
        Glob(pattern: '*.manifest', weight: 50, caseSensitive: false),
        Glob(pattern: '*.m4', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mf', weight: 50, caseSensitive: false),
        Glob(pattern: '*.MF', weight: 50, caseSensitive: false),
        Glob(pattern: '*.meta', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mdo', weight: 50, caseSensitive: false),
        Glob(pattern: '*.n3', weight: 50, caseSensitive: false),
        Glob(pattern: '*.pen', weight: 50, caseSensitive: false),
        Glob(pattern: '*.pod', weight: 50, caseSensitive: false),
        Glob(pattern: '*.pom', weight: 50, caseSensitive: false),
        Glob(pattern: '*.project', weight: 50, caseSensitive: false),
        Glob(pattern: '*.rng', weight: 50, caseSensitive: false),
        Glob(pattern: '*.rnx', weight: 50, caseSensitive: false),
        Glob(pattern: '*.roles', weight: 50, caseSensitive: false),
        Glob(pattern: '*.schemas', weight: 50, caseSensitive: false),
        Glob(pattern: '*.tld', weight: 50, caseSensitive: false),
        Glob(pattern: '*.types', weight: 50, caseSensitive: false),
        Glob(pattern: '*.vm', weight: 50, caseSensitive: false),
        Glob(pattern: '*.vsl', weight: 50, caseSensitive: false),
        Glob(pattern: '*.wsdd', weight: 50, caseSensitive: false),
        Glob(pattern: '*.xargs', weight: 50, caseSensitive: false),
        Glob(pattern: '*.xcat', weight: 50, caseSensitive: false),
        Glob(pattern: '*.xegrm', weight: 50, caseSensitive: false),
        Glob(pattern: '*.xgrm', weight: 50, caseSensitive: false),
        Glob(pattern: '*.xlex', weight: 50, caseSensitive: false),
        Glob(pattern: '*.xlog', weight: 50, caseSensitive: false),
        Glob(pattern: '*.xmap', weight: 50, caseSensitive: false),
        Glob(pattern: '*.xroles', weight: 50, caseSensitive: false),
        Glob(pattern: '*.xsamples', weight: 50, caseSensitive: false),
        Glob(pattern: '*.xsp', weight: 50, caseSensitive: false),
        Glob(pattern: '*.xtest', weight: 50, caseSensitive: false),
        Glob(pattern: '*.xweb', weight: 50, caseSensitive: false),
        Glob(pattern: '*.xwelcome', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 20,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'This is TeX,',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'This is METAFONT,',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '/*',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '//',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: ';;',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '0xfeff',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '0xfffe',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '0xefbbbf',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'text/prs.fallenstein.rst': [
    RegistryEntry(
      mediaType: 'text/prs.fallenstein.rst',
      subclassOf: [],
      alias: [],
    ),
  ],
  'text/prs.lines.tag': [
    RegistryEntry(
      mediaType: 'text/prs.lines.tag',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.dsc', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/red': [RegistryEntry(mediaType: 'text/red', subclassOf: [], alias: [])],
  'text/rfc822-headers': [
    RegistryEntry(mediaType: 'text/rfc822-headers', subclassOf: [], alias: []),
  ],
  'text/richtext': [
    RegistryEntry(
      mediaType: 'text/richtext',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.rtx', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/rtp-enc-aescm128': [
    RegistryEntry(
      mediaType: 'text/rtp-enc-aescm128',
      subclassOf: [],
      alias: [],
    ),
  ],
  'text/rtx': [RegistryEntry(mediaType: 'text/rtx', subclassOf: [], alias: [])],
  'text/sgml': [
    RegistryEntry(
      mediaType: 'text/sgml',
      subclassOf: [],
      alias: [],
      globs: [
        Glob(pattern: '*.sgml', weight: 50, caseSensitive: false),
        Glob(pattern: '*.sgm', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'text/t140': [
    RegistryEntry(mediaType: 'text/t140', subclassOf: [], alias: []),
  ],
  'text/tab-separated-values': [
    RegistryEntry(
      mediaType: 'text/tab-separated-values',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.tsv', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/troff': [
    RegistryEntry(
      mediaType: 'text/troff',
      subclassOf: [],
      alias: [
        'application/x-troff',
        'application/x-troff-man',
        'application/x-troff-me',
        'application/x-troff-ms',
      ],
      globs: [
        Glob(pattern: '*.t', weight: 50, caseSensitive: false),
        Glob(pattern: '*.tr', weight: 50, caseSensitive: false),
        Glob(pattern: '*.roff', weight: 50, caseSensitive: false),
        Glob(pattern: '*.nroff', weight: 50, caseSensitive: false),
        Glob(pattern: '*.man', weight: 50, caseSensitive: false),
        Glob(pattern: '*.me', weight: 50, caseSensitive: false),
        Glob(pattern: '*.ms', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '.\\"',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '\'\\"',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '\'.\\"',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '\\"',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '\'\'\'',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'text/ulpfec': [
    RegistryEntry(mediaType: 'text/ulpfec', subclassOf: [], alias: []),
  ],
  'text/uri-list': [
    RegistryEntry(
      mediaType: 'text/uri-list',
      subclassOf: [],
      alias: [],
      globs: [
        Glob(pattern: '*.uri', weight: 50, caseSensitive: false),
        Glob(pattern: '*.uris', weight: 50, caseSensitive: false),
        Glob(pattern: '*.urls', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'text/vnd.abc': [
    RegistryEntry(mediaType: 'text/vnd.abc', subclassOf: [], alias: []),
  ],
  'text/vnd.curl': [
    RegistryEntry(
      mediaType: 'text/vnd.curl',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.curl', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/vnd.curl.dcurl': [
    RegistryEntry(
      mediaType: 'text/vnd.curl.dcurl',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.dcurl', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/vnd.curl.scurl': [
    RegistryEntry(
      mediaType: 'text/vnd.curl.scurl',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.scurl', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/vnd.curl.mcurl': [
    RegistryEntry(
      mediaType: 'text/vnd.curl.mcurl',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.mcurl', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/vnd.dmclientscript': [
    RegistryEntry(
      mediaType: 'text/vnd.dmclientscript',
      subclassOf: [],
      alias: [],
    ),
  ],
  'text/vnd.esmertec.theme-descriptor': [
    RegistryEntry(
      mediaType: 'text/vnd.esmertec.theme-descriptor',
      subclassOf: [],
      alias: [],
    ),
  ],
  'text/vnd.fly': [
    RegistryEntry(
      mediaType: 'text/vnd.fly',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.fly', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/vnd.fmi.flexstor': [
    RegistryEntry(
      mediaType: 'text/vnd.fmi.flexstor',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.flx', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/vnd.graphviz': [
    RegistryEntry(
      mediaType: 'text/vnd.graphviz',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.gv', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.regex,
              offset: '0',
              value: '(?s)^\\s*(?:strict\\s+)?(?:di)?graph\\b',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.regex,
              offset: '0',
              value:
                  '(?s)^(?:\\s*//[^\\n]*\n){1,10}\\s*(?:strict\\s+)?(?:di)?graph\\b',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.regex,
              offset: '0',
              value:
                  '(?s)^\\s*/\\*.{0,1024}?\\*/\\s*(?:strict\\s+)?(?:di)?graph\\b',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'text/vnd.in3d.3dml': [
    RegistryEntry(
      mediaType: 'text/vnd.in3d.3dml',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.3dml', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/vnd.in3d.spot': [
    RegistryEntry(
      mediaType: 'text/vnd.in3d.spot',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.spot', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/vnd.iptc.anpa': [
    RegistryEntry(
      mediaType: 'text/vnd.iptc.anpa',
      acronym: IntlString.constant('ANPA'),
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.anpa', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '\x16\x16\x01',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'text/vnd.iptc.newsml': [
    RegistryEntry(mediaType: 'text/vnd.iptc.newsml', subclassOf: [], alias: []),
  ],
  'text/vnd.iptc.nitf': [
    RegistryEntry(mediaType: 'text/vnd.iptc.nitf', subclassOf: [], alias: []),
  ],
  'text/vnd.latex-z': [
    RegistryEntry(mediaType: 'text/vnd.latex-z', subclassOf: [], alias: []),
  ],
  'text/vnd.motorola.reflex': [
    RegistryEntry(
      mediaType: 'text/vnd.motorola.reflex',
      subclassOf: [],
      alias: [],
    ),
  ],
  'text/vnd.ms-mediapackage': [
    RegistryEntry(
      mediaType: 'text/vnd.ms-mediapackage',
      subclassOf: [],
      alias: [],
    ),
  ],
  'text/vnd.net2phone.commcenter.command': [
    RegistryEntry(
      mediaType: 'text/vnd.net2phone.commcenter.command',
      subclassOf: [],
      alias: [],
    ),
  ],
  'text/vnd.si.uricatalogue': [
    RegistryEntry(
      mediaType: 'text/vnd.si.uricatalogue',
      subclassOf: [],
      alias: [],
    ),
  ],
  'text/vnd.sun.j2me.app-descriptor': [
    RegistryEntry(
      mediaType: 'text/vnd.sun.j2me.app-descriptor',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.jad', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/vnd.trolltech.linguist': [
    RegistryEntry(
      mediaType: 'text/vnd.trolltech.linguist',
      subclassOf: [],
      alias: [],
    ),
  ],
  'text/vnd.wap.si': [
    RegistryEntry(mediaType: 'text/vnd.wap.si', subclassOf: [], alias: []),
  ],
  'text/vnd.wap.sl': [
    RegistryEntry(mediaType: 'text/vnd.wap.sl', subclassOf: [], alias: []),
  ],
  'text/vnd.wap.wml': [
    RegistryEntry(
      mediaType: 'text/vnd.wap.wml',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.wml', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/vnd.wap.wmlscript': [
    RegistryEntry(
      mediaType: 'text/vnd.wap.wmlscript',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.wmls', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/vtt': [
    RegistryEntry(
      mediaType: 'text/vtt',
      acronym: IntlString.constant('WebVTT'),
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.vtt', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 40,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'WEBVTT\r',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'WEBVTT\n',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.byte,
              offset: '0',
              value: '0xfeff',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '2',
                  value: 'WEBVTT\r',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '2',
                  value: 'WEBVTT\n',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
            Match.factory(
              type: MatchType.byte,
              offset: '0',
              value: '0xfeff',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '2',
                  value: 'WEBVTT\r',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '2',
                  value: 'WEBVTT\n',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
            Match.factory(
              type: MatchType.byte,
              offset: '0',
              value: '0xefbbbf',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: 'WEBVTT\r',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: 'WEBVTT\n',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'WEBVTT FILE\r',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'WEBVTT FILE\n',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
        Magic(
          priority: 30,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'WEBVTT ',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '10:50',
                  value: '\n\n',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'WEBVTT ',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '10:50',
                  value: '\r\r',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'WEBVTT ',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '10:50',
                  value: '\r\n\r\n',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'text/x-awk': [
    RegistryEntry(
      mediaType: 'text/x-awk',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.awk', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#!/bin/gawk',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#! /bin/gawk',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#!/usr/bin/gawk',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#! /usr/bin/gawk',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#!/usr/local/bin/gawk',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#! /usr/local/bin/gawk',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#!/bin/awk',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#! /bin/awk',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#!/usr/bin/awk',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#! /usr/bin/awk',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'text/x-basic': [
    RegistryEntry(
      mediaType: 'text/x-basic',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: '*.bas', weight: 50, caseSensitive: false),
        Glob(pattern: '*.Bas', weight: 50, caseSensitive: false),
        Glob(pattern: '*.BAS', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'text/x-c++hdr': [
    RegistryEntry(
      mediaType: 'text/x-c++hdr',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: '*.hpp', weight: 50, caseSensitive: false),
        Glob(pattern: '*.hxx', weight: 50, caseSensitive: false),
        Glob(pattern: '*.hh', weight: 50, caseSensitive: false),
        Glob(pattern: '*.H', weight: 50, caseSensitive: false),
        Glob(pattern: '*.h++', weight: 50, caseSensitive: false),
        Glob(pattern: '*.hp', weight: 50, caseSensitive: false),
        Glob(pattern: '*.HPP', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'text/x-c++src': [
    RegistryEntry(
      mediaType: 'text/x-c++src',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: '*.cpp', weight: 50, caseSensitive: false),
        Glob(pattern: '*.cxx', weight: 50, caseSensitive: false),
        Glob(pattern: '*.cc', weight: 50, caseSensitive: false),
        Glob(pattern: '*.C', weight: 50, caseSensitive: false),
        Glob(pattern: '*.c++', weight: 50, caseSensitive: false),
        Glob(pattern: '*.CPP', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'text/x-cgi': [
    RegistryEntry(
      mediaType: 'text/x-cgi',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.cgi', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-chdr': [
    RegistryEntry(
      mediaType: 'text/x-chdr',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.h', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 30,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#ifndef ',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'text/x-clojure': [
    RegistryEntry(
      mediaType: 'text/x-clojure',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.clj', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-coffeescript': [
    RegistryEntry(
      mediaType: 'text/x-coffeescript',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.coffee', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-csrc': [
    RegistryEntry(
      mediaType: 'text/x-csrc',
      subclassOf: ['text/plain'],
      alias: ['text/x-c'],
      globs: [Glob(pattern: '*.c', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 30,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#include ',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'text/x-csharp': [
    RegistryEntry(
      mediaType: 'text/x-csharp',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.cs', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-cobol': [
    RegistryEntry(
      mediaType: 'text/x-cobol',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: '*.cbl', weight: 50, caseSensitive: false),
        Glob(pattern: '*.Cbl', weight: 50, caseSensitive: false),
        Glob(pattern: '*.CBL', weight: 50, caseSensitive: false),
        Glob(pattern: '*.cob', weight: 50, caseSensitive: false),
        Glob(pattern: '*.Cob', weight: 50, caseSensitive: false),
        Glob(pattern: '*.COB', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'text/x-coldfusion': [
    RegistryEntry(
      mediaType: 'text/x-coldfusion',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: '*.cfm', weight: 50, caseSensitive: false),
        Glob(pattern: '*.cfml', weight: 50, caseSensitive: false),
        Glob(pattern: '*.cfc', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'text/x-common-lisp': [
    RegistryEntry(
      mediaType: 'text/x-common-lisp',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: '*.cl', weight: 50, caseSensitive: false),
        Glob(pattern: '*.jl', weight: 50, caseSensitive: false),
        Glob(pattern: '*.lisp', weight: 50, caseSensitive: false),
        Glob(pattern: '*.lsp', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'text/x-diff': [
    RegistryEntry(
      mediaType: 'text/x-diff',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: '*.diff', weight: 50, caseSensitive: false),
        Glob(pattern: '*.patch', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'diff\\ ',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '***\\ ',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'Only\\ in\\ ',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'Common\\ subdirectories:\\ ',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'Index:',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'text/x-eiffel': [
    RegistryEntry(
      mediaType: 'text/x-eiffel',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.e', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-emacs-lisp': [
    RegistryEntry(
      mediaType: 'text/x-emacs-lisp',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.el', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-erlang': [
    RegistryEntry(
      mediaType: 'text/x-erlang',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.erl', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-expect': [
    RegistryEntry(
      mediaType: 'text/x-expect',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.exp', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-forth': [
    RegistryEntry(
      mediaType: 'text/x-forth',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.4th', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-fortran': [
    RegistryEntry(
      mediaType: 'text/x-fortran',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: '*.f', weight: 50, caseSensitive: false),
        Glob(pattern: '*.F', weight: 50, caseSensitive: false),
        Glob(pattern: '*.for', weight: 50, caseSensitive: false),
        Glob(pattern: '*.f77', weight: 50, caseSensitive: false),
        Glob(pattern: '*.f90', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'text/x-go': [
    RegistryEntry(
      mediaType: 'text/x-go',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.go', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-groovy': [
    RegistryEntry(
      mediaType: 'text/x-groovy',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.groovy', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-haskell': [
    RegistryEntry(
      mediaType: 'text/x-haskell',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: '*.hs', weight: 50, caseSensitive: false),
        Glob(pattern: '*.lhs', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'text/x-idl': [
    RegistryEntry(
      mediaType: 'text/x-idl',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.idl', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-ini': [
    RegistryEntry(
      mediaType: 'text/x-ini',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.ini', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-java-source': [
    RegistryEntry(
      mediaType: 'text/x-java-source',
      subclassOf: ['text/plain'],
      alias: ['text/x-java'],
      globs: [Glob(pattern: '*.java', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-java-properties': [
    RegistryEntry(
      mediaType: 'text/x-java-properties',
      subclassOf: ['text/plain'],
      alias: ['text/x-properties', 'text/properties'],
      globs: [Glob(pattern: '*.properties', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-jsp': [
    RegistryEntry(
      mediaType: 'text/x-jsp',
      subclassOf: ['text/plain'],
      alias: ['application/x-httpd-jsp'],
      globs: [Glob(pattern: '*.jsp', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '<%@',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '<%--',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'text/x-less': [
    RegistryEntry(
      mediaType: 'text/x-less',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.less', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-lex': [
    RegistryEntry(
      mediaType: 'text/x-lex',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.l', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-log': [
    RegistryEntry(
      mediaType: 'text/x-log',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.log', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-lua': [
    RegistryEntry(
      mediaType: 'text/x-lua',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.lua', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-ml': [
    RegistryEntry(
      mediaType: 'text/x-ml',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.ml', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-matlab': [
    RegistryEntry(
      mediaType: 'text/x-matlab',
      subclassOf: ['text/plain'],
      alias: [],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'function [',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
        Magic(
          priority: 40,
          matches: [
            Match.factory(
              type: MatchType.regex,
              offset: '0',
              value: 'function [a-zA-Z][A-Za-z0-9_]{0,62}\\s*=',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
        Magic(
          priority: 40,
          matches: [
            Match.factory(
              type: MatchType.regex,
              offset: '0',
              value: 'function [a-zA-Z][A-Za-z0-9_]{0,62}[\\r\\n]',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
        Magic(
          priority: 25,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '%',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '2:120',
                  value: '\n%',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '%',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '2:120',
                  value: '\r%',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '%%',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'text/x-modula': [
    RegistryEntry(
      mediaType: 'text/x-modula',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: '*.m3', weight: 50, caseSensitive: false),
        Glob(pattern: '*.i3', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mg', weight: 50, caseSensitive: false),
        Glob(pattern: '*.ig', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'text/x-objcsrc': [
    RegistryEntry(
      mediaType: 'text/x-objcsrc',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.m', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-ocaml': [
    RegistryEntry(
      mediaType: 'text/x-ocaml',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: '*.ocaml', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mli', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'text/x-pascal': [
    RegistryEntry(
      mediaType: 'text/x-pascal',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: '*.p', weight: 50, caseSensitive: false),
        Glob(pattern: '*.pp', weight: 50, caseSensitive: false),
        Glob(pattern: '*.pas', weight: 50, caseSensitive: false),
        Glob(pattern: '*.PAS', weight: 50, caseSensitive: false),
        Glob(pattern: '*.dpr', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'text/x-perl': [
    RegistryEntry(
      mediaType: 'text/x-perl',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: '*.pl', weight: 50, caseSensitive: false),
        Glob(pattern: '*.pm', weight: 50, caseSensitive: false),
        Glob(pattern: '*.al', weight: 50, caseSensitive: false),
        Glob(pattern: '*.perl', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'eval \\"exec /usr/local/bin/perl',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#!/bin/perl',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#!/bin/env perl',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#!/usr/bin/perl',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#!/usr/local/bin/perl',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'text/x-php': [
    RegistryEntry(
      mediaType: 'text/x-php',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: '*.php', weight: 50, caseSensitive: false),
        Glob(pattern: '*.php3', weight: 50, caseSensitive: false),
        Glob(pattern: '*.php4', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '<?php',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'text/x-prolog': [
    RegistryEntry(
      mediaType: 'text/x-prolog',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.pro', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-python': [
    RegistryEntry(
      mediaType: 'text/x-python',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.py', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#!/bin/python',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#! /bin/python',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'eval "exec /bin/python',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#!/usr/bin/python',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#! /usr/bin/python',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'eval "exec /usr/bin/python',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#!/usr/local/bin/python',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#! /usr/local/bin/python',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'eval "exec /usr/local/bin/python',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '1',
              value: '/bin/env python',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'text/x-rst': [
    RegistryEntry(
      mediaType: 'text/x-rst',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: '*.rest', weight: 50, caseSensitive: false),
        Glob(pattern: '*.rst', weight: 50, caseSensitive: false),
        Glob(pattern: '*.restx', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'text/x-rexx': [
    RegistryEntry(
      mediaType: 'text/x-rexx',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.rexx', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-ruby': [
    RegistryEntry(
      mediaType: 'text/x-ruby',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.rb', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-scala': [
    RegistryEntry(
      mediaType: 'text/x-scala',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.scala', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-scheme': [
    RegistryEntry(
      mediaType: 'text/x-scheme',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.scm', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-sed': [
    RegistryEntry(
      mediaType: 'text/x-sed',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.sed', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-sql': [
    RegistryEntry(
      mediaType: 'text/x-sql',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.sql', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-setext': [
    RegistryEntry(
      mediaType: 'text/x-setext',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.etx', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-stsrc': [
    RegistryEntry(
      mediaType: 'text/x-stsrc',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.st', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-tcl': [
    RegistryEntry(
      mediaType: 'text/x-tcl',
      subclassOf: ['text/plain'],
      alias: ['application/x-tcl'],
      globs: [
        Glob(pattern: '*.itk', weight: 50, caseSensitive: false),
        Glob(pattern: '*.tcl', weight: 50, caseSensitive: false),
        Glob(pattern: '*.tk', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'text/x-tika-text-based-message': [
    RegistryEntry(
      mediaType: 'text/x-tika-text-based-message',
      subclassOf: [],
      alias: [],
    ),
  ],
  'text/x-uuencode': [
    RegistryEntry(
      mediaType: 'text/x-uuencode',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.uu', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-vbasic': [
    RegistryEntry(
      mediaType: 'text/x-vbasic',
      subclassOf: ['text/x-basic'],
      alias: [],
      globs: [
        Glob(pattern: '*.cls', weight: 50, caseSensitive: false),
        Glob(pattern: '*.Cls', weight: 50, caseSensitive: false),
        Glob(pattern: '*.CLS', weight: 50, caseSensitive: false),
        Glob(pattern: '*.frm', weight: 50, caseSensitive: false),
        Glob(pattern: '*.Frm', weight: 50, caseSensitive: false),
        Glob(pattern: '*.FRM', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'text/x-vbdotnet': [
    RegistryEntry(
      mediaType: 'text/x-vbdotnet',
      subclassOf: ['text/x-vbasic'],
      alias: [],
      globs: [Glob(pattern: '*.vb', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-vbscript': [
    RegistryEntry(
      mediaType: 'text/x-vbscript',
      subclassOf: ['text/x-vbasic'],
      alias: [],
      globs: [Glob(pattern: '*.vbs', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-vcalendar': [
    RegistryEntry(
      mediaType: 'text/x-vcalendar',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.vcs', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'BEGIN:VCALENDAR',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '15:30',
                  value: 'VERSION:1.0',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'text/x-vcard': [
    RegistryEntry(
      mediaType: 'text/x-vcard',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.vcf', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'BEGIN:VCARD',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'text/x-verilog': [
    RegistryEntry(
      mediaType: 'text/x-verilog',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.v', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-vhdl': [
    RegistryEntry(
      mediaType: 'text/x-vhdl',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: '*.vhd', weight: 50, caseSensitive: false),
        Glob(pattern: '*.vhdl', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'text/x-web-markdown': [
    RegistryEntry(
      mediaType: 'text/x-web-markdown',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: '*.md', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mdtext', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mkd', weight: 50, caseSensitive: false),
        Glob(pattern: '*.markdown', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'text/x-yacc': [
    RegistryEntry(
      mediaType: 'text/x-yacc',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.y', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-yaml': [
    RegistryEntry(
      mediaType: 'text/x-yaml',
      subclassOf: ['text/plain'],
      alias: [
        'application/x-yaml',
        'application/x-yml',
        'application/yaml',
        'text/vnd.yaml',
        'text/yaml',
        'text/x-yml',
      ],
      globs: [
        Glob(pattern: '*.yaml', weight: 50, caseSensitive: false),
        Glob(pattern: '*.yml', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'text/x-asciidoc': [
    RegistryEntry(
      mediaType: 'text/x-asciidoc',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: '*.asciidoc', weight: 50, caseSensitive: false),
        Glob(pattern: '*.adoc', weight: 50, caseSensitive: false),
        Glob(pattern: '*.ad', weight: 50, caseSensitive: false),
        Glob(pattern: '*.ad.txt', weight: 50, caseSensitive: false),
        Glob(pattern: '*.adoc.txt', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'text/x-d': [
    RegistryEntry(
      mediaType: 'text/x-d',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.d', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-haml': [
    RegistryEntry(
      mediaType: 'text/x-haml',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.haml', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-haxe': [
    RegistryEntry(
      mediaType: 'text/x-haxe',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.hx', weight: 50, caseSensitive: false)],
    ),
  ],
  'text/x-rsrc': [
    RegistryEntry(
      mediaType: 'text/x-rsrc',
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.r', weight: 50, caseSensitive: false)],
    ),
  ],
};
