// Copyright 2026 The Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Generated by tool/loader.dart
// ignore_for_file: non_constant_identifier_names,unused_import

import 'package:betto_mediatype_detector/betto_mediatype_detector.dart';
import 'package:betto_common/string.dart';
import 'package:meta/meta.dart';

@internal
final Registry mimeinfoDbAudio = {
  'audio/32kadpcm': [
    RegistryEntry(mediaType: 'audio/32kadpcm', subclassOf: [], alias: []),
  ],
  'audio/3gpp': [
    RegistryEntry(mediaType: 'audio/3gpp', subclassOf: [], alias: []),
  ],
  'audio/3gpp2': [
    RegistryEntry(mediaType: 'audio/3gpp2', subclassOf: [], alias: []),
  ],
  'audio/ac3': [
    RegistryEntry(
      mediaType: 'audio/ac3',
      acronym: IntlString.constant('AC3'),
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.ac3', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 40,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '0x0b77',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '0x0b77',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '5',
                  value: '0x00',
                  mask: '0xF8',
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '5',
                  value: '0x08',
                  mask: '0xF8',
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '5',
                  value: '0x10',
                  mask: '0xF8',
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '5',
                  value: '0x18',
                  mask: '0xF8',
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '5',
                  value: '0x20',
                  mask: '0xF8',
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '5',
                  value: '0x28',
                  mask: '0xF8',
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '5',
                  value: '0x30',
                  mask: '0xF8',
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '5',
                  value: '0x38',
                  mask: '0xF8',
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '5',
                  value: '0x40',
                  mask: '0xF8',
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/eac3': [
    RegistryEntry(
      mediaType: 'audio/eac3',
      acronym: IntlString.constant('EAC3'),
      subclassOf: ['audio/ac3'],
      alias: [],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '0x0b77',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '5',
                  value: '0x58',
                  mask: '0xF8',
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '5',
                  value: '0x60',
                  mask: '0xF8',
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '5',
                  value: '0x68',
                  mask: '0xF8',
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '5',
                  value: '0x70',
                  mask: '0xF8',
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '5',
                  value: '0x78',
                  mask: '0xF8',
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '5',
                  value: '0x80',
                  mask: '0xF8',
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/adpcm': [
    RegistryEntry(
      mediaType: 'audio/adpcm',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.adp', weight: 50, caseSensitive: false)],
    ),
  ],
  'audio/amr': [
    RegistryEntry(
      mediaType: 'audio/amr',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.amr', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 40,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#!AMR\n',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#!AMR',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/amr-wb': [
    RegistryEntry(
      mediaType: 'audio/amr-wb',
      subclassOf: ['audio/amr'],
      alias: [],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#!AMR-WB\n',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/amr-wb+': [
    RegistryEntry(
      mediaType: 'audio/amr-wb+',
      subclassOf: ['audio/amr'],
      alias: [],
    ),
  ],
  'audio/asc': [
    RegistryEntry(mediaType: 'audio/asc', subclassOf: [], alias: []),
  ],
  'audio/basic': [
    RegistryEntry(
      mediaType: 'audio/basic',
      subclassOf: [],
      alias: [],
      globs: [
        Glob(pattern: '*.au', weight: 50, caseSensitive: false),
        Glob(pattern: '*.snd', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 20,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '.snd',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.big32,
                  offset: '12',
                  value: '1',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.big32,
                  offset: '12',
                  value: '2',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.big32,
                  offset: '12',
                  value: '3',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.big32,
                  offset: '12',
                  value: '4',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.big32,
                  offset: '12',
                  value: '5',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.big32,
                  offset: '12',
                  value: '6',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.big32,
                  offset: '12',
                  value: '7',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '.snd\x00\x00\x00',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/bv16': [
    RegistryEntry(mediaType: 'audio/bv16', subclassOf: [], alias: []),
  ],
  'audio/bv32': [
    RegistryEntry(mediaType: 'audio/bv32', subclassOf: [], alias: []),
  ],
  'audio/clearmode': [
    RegistryEntry(mediaType: 'audio/clearmode', subclassOf: [], alias: []),
  ],
  'audio/cn': [RegistryEntry(mediaType: 'audio/cn', subclassOf: [], alias: [])],
  'audio/dat12': [
    RegistryEntry(mediaType: 'audio/dat12', subclassOf: [], alias: []),
  ],
  'audio/dls': [
    RegistryEntry(mediaType: 'audio/dls', subclassOf: [], alias: []),
  ],
  'audio/dsr-es201108': [
    RegistryEntry(mediaType: 'audio/dsr-es201108', subclassOf: [], alias: []),
  ],
  'audio/dsr-es202050': [
    RegistryEntry(mediaType: 'audio/dsr-es202050', subclassOf: [], alias: []),
  ],
  'audio/dsr-es202211': [
    RegistryEntry(mediaType: 'audio/dsr-es202211', subclassOf: [], alias: []),
  ],
  'audio/dsr-es202212': [
    RegistryEntry(mediaType: 'audio/dsr-es202212', subclassOf: [], alias: []),
  ],
  'audio/dvi4': [
    RegistryEntry(mediaType: 'audio/dvi4', subclassOf: [], alias: []),
  ],
  'audio/evrc': [
    RegistryEntry(mediaType: 'audio/evrc', subclassOf: [], alias: []),
  ],
  'audio/evrc-qcp': [
    RegistryEntry(mediaType: 'audio/evrc-qcp', subclassOf: [], alias: []),
  ],
  'audio/evrc0': [
    RegistryEntry(mediaType: 'audio/evrc0', subclassOf: [], alias: []),
  ],
  'audio/evrc1': [
    RegistryEntry(mediaType: 'audio/evrc1', subclassOf: [], alias: []),
  ],
  'audio/evrcb': [
    RegistryEntry(mediaType: 'audio/evrcb', subclassOf: [], alias: []),
  ],
  'audio/evrcb0': [
    RegistryEntry(mediaType: 'audio/evrcb0', subclassOf: [], alias: []),
  ],
  'audio/evrcb1': [
    RegistryEntry(mediaType: 'audio/evrcb1', subclassOf: [], alias: []),
  ],
  'audio/evrcwb': [
    RegistryEntry(mediaType: 'audio/evrcwb', subclassOf: [], alias: []),
  ],
  'audio/evrcwb0': [
    RegistryEntry(mediaType: 'audio/evrcwb0', subclassOf: [], alias: []),
  ],
  'audio/evrcwb1': [
    RegistryEntry(mediaType: 'audio/evrcwb1', subclassOf: [], alias: []),
  ],
  'audio/example': [
    RegistryEntry(mediaType: 'audio/example', subclassOf: [], alias: []),
  ],
  'audio/g719': [
    RegistryEntry(mediaType: 'audio/g719', subclassOf: [], alias: []),
  ],
  'audio/g722': [
    RegistryEntry(mediaType: 'audio/g722', subclassOf: [], alias: []),
  ],
  'audio/g7221': [
    RegistryEntry(mediaType: 'audio/g7221', subclassOf: [], alias: []),
  ],
  'audio/g723': [
    RegistryEntry(mediaType: 'audio/g723', subclassOf: [], alias: []),
  ],
  'audio/g726-16': [
    RegistryEntry(mediaType: 'audio/g726-16', subclassOf: [], alias: []),
  ],
  'audio/g726-24': [
    RegistryEntry(mediaType: 'audio/g726-24', subclassOf: [], alias: []),
  ],
  'audio/g726-32': [
    RegistryEntry(mediaType: 'audio/g726-32', subclassOf: [], alias: []),
  ],
  'audio/g726-40': [
    RegistryEntry(mediaType: 'audio/g726-40', subclassOf: [], alias: []),
  ],
  'audio/g728': [
    RegistryEntry(mediaType: 'audio/g728', subclassOf: [], alias: []),
  ],
  'audio/g729': [
    RegistryEntry(mediaType: 'audio/g729', subclassOf: [], alias: []),
  ],
  'audio/g7291': [
    RegistryEntry(mediaType: 'audio/g7291', subclassOf: [], alias: []),
  ],
  'audio/g729d': [
    RegistryEntry(mediaType: 'audio/g729d', subclassOf: [], alias: []),
  ],
  'audio/g729e': [
    RegistryEntry(mediaType: 'audio/g729e', subclassOf: [], alias: []),
  ],
  'audio/gsm': [
    RegistryEntry(mediaType: 'audio/gsm', subclassOf: [], alias: []),
  ],
  'audio/gsm-efr': [
    RegistryEntry(mediaType: 'audio/gsm-efr', subclassOf: [], alias: []),
  ],
  'audio/ilbc': [
    RegistryEntry(mediaType: 'audio/ilbc', subclassOf: [], alias: []),
  ],
  'audio/l16': [
    RegistryEntry(mediaType: 'audio/l16', subclassOf: [], alias: []),
  ],
  'audio/l20': [
    RegistryEntry(mediaType: 'audio/l20', subclassOf: [], alias: []),
  ],
  'audio/l24': [
    RegistryEntry(mediaType: 'audio/l24', subclassOf: [], alias: []),
  ],
  'audio/l8': [RegistryEntry(mediaType: 'audio/l8', subclassOf: [], alias: [])],
  'audio/lpc': [
    RegistryEntry(mediaType: 'audio/lpc', subclassOf: [], alias: []),
  ],
  'audio/midi': [
    RegistryEntry(
      mediaType: 'audio/midi',
      acronym: IntlString.constant('MIDI'),
      subclassOf: [],
      alias: [],
      globs: [
        Glob(pattern: '*.mid', weight: 50, caseSensitive: false),
        Glob(pattern: '*.midi', weight: 50, caseSensitive: false),
        Glob(pattern: '*.kar', weight: 50, caseSensitive: false),
        Glob(pattern: '*.rmi', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 20,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'MThd',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/mobile-xmf': [
    RegistryEntry(mediaType: 'audio/mobile-xmf', subclassOf: [], alias: []),
  ],
  'audio/mp4': [
    RegistryEntry(
      mediaType: 'audio/mp4',
      subclassOf: ['video/mp4'],
      alias: ['audio/x-m4a', 'audio/x-mp4a'],
      globs: [
        Glob(pattern: '*.mp4a', weight: 50, caseSensitive: false),
        Glob(pattern: '*.m4a', weight: 50, caseSensitive: false),
        Glob(pattern: '*.m4b', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftypM4A ',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftypM4B ',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftypF4A ',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftypF4B ',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/mp4a-latm': [
    RegistryEntry(mediaType: 'audio/mp4a-latm', subclassOf: [], alias: []),
  ],
  'audio/mpa': [
    RegistryEntry(mediaType: 'audio/mpa', subclassOf: [], alias: []),
  ],
  'audio/mpa-robust': [
    RegistryEntry(mediaType: 'audio/mpa-robust', subclassOf: [], alias: []),
  ],
  'audio/mpeg': [
    RegistryEntry(
      mediaType: 'audio/mpeg',
      acronym: IntlString.constant('MP3'),
      subclassOf: [],
      alias: ['audio/x-mpeg'],
      globs: [
        Glob(pattern: '*.mpga', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mp2', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mp2a', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mp3', weight: 50, caseSensitive: false),
        Glob(pattern: '*.m2a', weight: 50, caseSensitive: false),
        Glob(pattern: '*.m3a', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '0xfff2',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '0xfff3',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '0xfff4',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '0xfff5',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '0xfff6',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '0xfff7',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '0xfffa',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '0xfffb',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '0xfffc',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '0xfffd',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '0xffe3',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'ID3',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.regex,
                  offset: '512:8192',
                  value: '\\xFF[\\xE3\\xF2-\\xF7\\xFA-\\xFD\\xFF]',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
            Match.factory(
              type: MatchType.regex,
              offset: '0',
              value: '(?:\\x0D\\x0A|\\x00{1,1024})(?:\\xff[\\xe3\\xf2\\xf3\\xf4\\xf5\\xf6\\xf7\\xf8\\xf9\\xfa\\xfb\\xfc\\xfd\\xfe\\xff]|ID3)',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
        Magic(
          priority: 10,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'ID3',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/mpeg4-generic': [
    RegistryEntry(mediaType: 'audio/mpeg4-generic', subclassOf: [], alias: []),
  ],
  'audio/ogg': [
    RegistryEntry(
      mediaType: 'audio/ogg',
      subclassOf: ['application/ogg'],
      alias: [],
      globs: [Glob(pattern: '*.oga', weight: 50, caseSensitive: false)],
    ),
  ],
  'audio/vorbis': [
    RegistryEntry(
      mediaType: 'audio/vorbis',
      subclassOf: ['audio/ogg'],
      alias: ['application/x-ogg'],
      globs: [Glob(pattern: '*.ogg', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'OggS\x00.......................\x01vorbis',
              mask: '0xFFFFFFFF00000000000000000000000000000000000000000000000000FFFFFFFFFFFF',
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-psf': [
    RegistryEntry(
      mediaType: 'audio/x-psf',
      subclassOf: [],
      alias: [],
      globs: [
        Glob(pattern: '*.psf1', weight: 50, caseSensitive: false),
        Glob(pattern: '*.psflib', weight: 50, caseSensitive: false),
        Glob(pattern: '*.minipsf', weight: 50, caseSensitive: false),
        Glob(pattern: '*.minipsf1', weight: 50, caseSensitive: false),
        Glob(pattern: '*.gslib', weight: 50, caseSensitive: false),
        Glob(pattern: '*.minigsf', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'PSF',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: '\x01',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: '\x02',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: '\x11',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: '\x12',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: '\x13',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: '!',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: '"',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: '#',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: 'A',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-sap': [
    RegistryEntry(
      mediaType: 'audio/x-sap',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.sap', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'SAP\r\n',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-oggflac': [
    RegistryEntry(
      mediaType: 'audio/x-oggflac',
      subclassOf: ['audio/ogg'],
      alias: ['audio/x-ogg-flac'],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'OggS\x00.......................FLAC',
              mask: '0xFFFFFFFF00000000000000000000000000000000000000000000000000FFFFFF',
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-oggpcm': [
    RegistryEntry(
      mediaType: 'audio/x-oggpcm',
      subclassOf: ['audio/ogg'],
      alias: ['audio/x-ogg-pcm'],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'OggS\x00.......................PCM     ',
              mask: '0xFFFFFFFF00000000000000000000000000000000000000000000000000FFFFFFFFFFFFFFFF',
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/opus': [
    RegistryEntry(
      mediaType: 'audio/opus',
      subclassOf: ['audio/ogg'],
      alias: [],
      globs: [Glob(pattern: '*.opus', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'OggS\x00.......................OpusHead',
              mask: '0xFFFFFFFF00000000000000000000000000000000000000000000000000FFFFFFFFFFFFFFFF',
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/speex': [
    RegistryEntry(
      mediaType: 'audio/speex',
      subclassOf: ['audio/ogg'],
      alias: ['application/x-speex'],
      globs: [Glob(pattern: '*.spx', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'OggS\x00.......................Speex   ',
              mask: '0xFFFFFFFF00000000000000000000000000000000000000000000000000FFFFFFFFFFFFFFFF',
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/parityfec': [
    RegistryEntry(mediaType: 'audio/parityfec', subclassOf: [], alias: []),
  ],
  'audio/pcma': [
    RegistryEntry(mediaType: 'audio/pcma', subclassOf: [], alias: []),
  ],
  'audio/pcma-wb': [
    RegistryEntry(mediaType: 'audio/pcma-wb', subclassOf: [], alias: []),
  ],
  'audio/pcmu-wb': [
    RegistryEntry(mediaType: 'audio/pcmu-wb', subclassOf: [], alias: []),
  ],
  'audio/pcmu': [
    RegistryEntry(mediaType: 'audio/pcmu', subclassOf: [], alias: []),
  ],
  'audio/prs.sid': [
    RegistryEntry(
      mediaType: 'audio/prs.sid',
      subclassOf: [],
      alias: [],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'PSID',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/qcelp': [
    RegistryEntry(mediaType: 'audio/qcelp', subclassOf: [], alias: []),
  ],
  'audio/red': [
    RegistryEntry(mediaType: 'audio/red', subclassOf: [], alias: []),
  ],
  'audio/rtp-enc-aescm128': [
    RegistryEntry(
      mediaType: 'audio/rtp-enc-aescm128',
      subclassOf: [],
      alias: [],
    ),
  ],
  'audio/rtp-midi': [
    RegistryEntry(mediaType: 'audio/rtp-midi', subclassOf: [], alias: []),
  ],
  'audio/rtx': [
    RegistryEntry(mediaType: 'audio/rtx', subclassOf: [], alias: []),
  ],
  'audio/smv': [
    RegistryEntry(mediaType: 'audio/smv', subclassOf: [], alias: []),
  ],
  'audio/smv0': [
    RegistryEntry(mediaType: 'audio/smv0', subclassOf: [], alias: []),
  ],
  'audio/smv-qcp': [
    RegistryEntry(mediaType: 'audio/smv-qcp', subclassOf: [], alias: []),
  ],
  'audio/sp-midi': [
    RegistryEntry(mediaType: 'audio/sp-midi', subclassOf: [], alias: []),
  ],
  'audio/t140c': [
    RegistryEntry(mediaType: 'audio/t140c', subclassOf: [], alias: []),
  ],
  'audio/t38': [
    RegistryEntry(mediaType: 'audio/t38', subclassOf: [], alias: []),
  ],
  'audio/telephone-event': [
    RegistryEntry(
      mediaType: 'audio/telephone-event',
      subclassOf: [],
      alias: [],
    ),
  ],
  'audio/tone': [
    RegistryEntry(mediaType: 'audio/tone', subclassOf: [], alias: []),
  ],
  'audio/ulpfec': [
    RegistryEntry(mediaType: 'audio/ulpfec', subclassOf: [], alias: []),
  ],
  'audio/vdvi': [
    RegistryEntry(mediaType: 'audio/vdvi', subclassOf: [], alias: []),
  ],
  'audio/vmr-wb': [
    RegistryEntry(mediaType: 'audio/vmr-wb', subclassOf: [], alias: []),
  ],
  'audio/vnd.3gpp.iufp': [
    RegistryEntry(mediaType: 'audio/vnd.3gpp.iufp', subclassOf: [], alias: []),
  ],
  'audio/vnd.4sb': [
    RegistryEntry(mediaType: 'audio/vnd.4sb', subclassOf: [], alias: []),
  ],
  'audio/vnd.audiokoz': [
    RegistryEntry(mediaType: 'audio/vnd.audiokoz', subclassOf: [], alias: []),
  ],
  'audio/vnd.adobe.soundbooth': [
    RegistryEntry(
      mediaType: 'audio/vnd.adobe.soundbooth',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.asnd', weight: 50, caseSensitive: false)],
    ),
  ],
  'audio/vnd.celp': [
    RegistryEntry(mediaType: 'audio/vnd.celp', subclassOf: [], alias: []),
  ],
  'audio/vnd.cisco.nse': [
    RegistryEntry(mediaType: 'audio/vnd.cisco.nse', subclassOf: [], alias: []),
  ],
  'audio/vnd.cmles.radio-events': [
    RegistryEntry(
      mediaType: 'audio/vnd.cmles.radio-events',
      subclassOf: [],
      alias: [],
    ),
  ],
  'audio/vnd.cns.anp1': [
    RegistryEntry(mediaType: 'audio/vnd.cns.anp1', subclassOf: [], alias: []),
  ],
  'audio/vnd.cns.inf1': [
    RegistryEntry(mediaType: 'audio/vnd.cns.inf1', subclassOf: [], alias: []),
  ],
  'audio/vnd.digital-winds': [
    RegistryEntry(
      mediaType: 'audio/vnd.digital-winds',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.eol', weight: 50, caseSensitive: false)],
    ),
  ],
  'audio/vnd.dlna.adts': [
    RegistryEntry(mediaType: 'audio/vnd.dlna.adts', subclassOf: [], alias: []),
  ],
  'audio/vnd.dolby.heaac.1': [
    RegistryEntry(
      mediaType: 'audio/vnd.dolby.heaac.1',
      subclassOf: [],
      alias: [],
    ),
  ],
  'audio/vnd.dolby.heaac.2': [
    RegistryEntry(
      mediaType: 'audio/vnd.dolby.heaac.2',
      subclassOf: [],
      alias: [],
    ),
  ],
  'audio/vnd.dolby.mlp': [
    RegistryEntry(mediaType: 'audio/vnd.dolby.mlp', subclassOf: [], alias: []),
  ],
  'audio/vnd.dolby.mps': [
    RegistryEntry(mediaType: 'audio/vnd.dolby.mps', subclassOf: [], alias: []),
  ],
  'audio/vnd.dolby.pl2': [
    RegistryEntry(mediaType: 'audio/vnd.dolby.pl2', subclassOf: [], alias: []),
  ],
  'audio/vnd.dolby.pl2x': [
    RegistryEntry(mediaType: 'audio/vnd.dolby.pl2x', subclassOf: [], alias: []),
  ],
  'audio/vnd.dolby.pl2z': [
    RegistryEntry(mediaType: 'audio/vnd.dolby.pl2z', subclassOf: [], alias: []),
  ],
  'audio/vnd.dts': [
    RegistryEntry(
      mediaType: 'audio/vnd.dts',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.dts', weight: 50, caseSensitive: false)],
    ),
  ],
  'audio/vnd.dts.hd': [
    RegistryEntry(
      mediaType: 'audio/vnd.dts.hd',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.dtshd', weight: 50, caseSensitive: false)],
    ),
  ],
  'audio/vnd.everad.plj': [
    RegistryEntry(mediaType: 'audio/vnd.everad.plj', subclassOf: [], alias: []),
  ],
  'audio/vnd.hns.audio': [
    RegistryEntry(mediaType: 'audio/vnd.hns.audio', subclassOf: [], alias: []),
  ],
  'audio/vnd.lucent.voice': [
    RegistryEntry(
      mediaType: 'audio/vnd.lucent.voice',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.lvp', weight: 50, caseSensitive: false)],
    ),
  ],
  'audio/vnd.ms-playready.media.pya': [
    RegistryEntry(
      mediaType: 'audio/vnd.ms-playready.media.pya',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.pya', weight: 50, caseSensitive: false)],
    ),
  ],
  'audio/vnd.nokia.mobile-xmf': [
    RegistryEntry(
      mediaType: 'audio/vnd.nokia.mobile-xmf',
      subclassOf: [],
      alias: [],
    ),
  ],
  'audio/vnd.nortel.vbk': [
    RegistryEntry(mediaType: 'audio/vnd.nortel.vbk', subclassOf: [], alias: []),
  ],
  'audio/vnd.nuera.ecelp4800': [
    RegistryEntry(
      mediaType: 'audio/vnd.nuera.ecelp4800',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.ecelp4800', weight: 50, caseSensitive: false)],
    ),
  ],
  'audio/vnd.nuera.ecelp7470': [
    RegistryEntry(
      mediaType: 'audio/vnd.nuera.ecelp7470',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.ecelp7470', weight: 50, caseSensitive: false)],
    ),
  ],
  'audio/vnd.nuera.ecelp9600': [
    RegistryEntry(
      mediaType: 'audio/vnd.nuera.ecelp9600',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.ecelp9600', weight: 50, caseSensitive: false)],
    ),
  ],
  'audio/vnd.octel.sbc': [
    RegistryEntry(mediaType: 'audio/vnd.octel.sbc', subclassOf: [], alias: []),
  ],
  'audio/vnd.qcelp': [
    RegistryEntry(mediaType: 'audio/vnd.qcelp', subclassOf: [], alias: []),
  ],
  'audio/vnd.rhetorex.32kadpcm': [
    RegistryEntry(
      mediaType: 'audio/vnd.rhetorex.32kadpcm',
      subclassOf: [],
      alias: [],
    ),
  ],
  'audio/vnd.sealedmedia.softseal.mpeg': [
    RegistryEntry(
      mediaType: 'audio/vnd.sealedmedia.softseal.mpeg',
      subclassOf: [],
      alias: [],
    ),
  ],
  'audio/vnd.vmx.cvsd': [
    RegistryEntry(mediaType: 'audio/vnd.vmx.cvsd', subclassOf: [], alias: []),
  ],
  'audio/vorbis-config': [
    RegistryEntry(mediaType: 'audio/vorbis-config', subclassOf: [], alias: []),
  ],
  'audio/x-aac': [
    RegistryEntry(
      mediaType: 'audio/x-aac',
      subclassOf: [],
      alias: ['audio/aac'],
      globs: [Glob(pattern: '*.aac', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 30,
          matches: [
            Match.factory(
              type: MatchType.regex,
              offset: '0',
              value: '(?s)\\xFF[\\xF0\\xF1\\xF8\\xF9].{2}.{100,2000}\\xFF[\\xF0\\xF1\\xF8\\xF9]',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
        Magic(
          priority: 40,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'ID3',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.regex,
                  offset: '512:8192',
                  value: '(?s)\\xFF[\\xF0\\xF1\\xF8\\xF9].{2}.{100,2000}\\xFF[\\xF0\\xF1\\xF8\\xF9]',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-adpcm': [
    RegistryEntry(
      mediaType: 'audio/x-adpcm',
      subclassOf: [],
      alias: [],
      magic: [
        Magic(
          priority: 20,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '.snd',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.big32,
                  offset: '12',
                  value: '23',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-aiff': [
    RegistryEntry(
      mediaType: 'audio/x-aiff',
      acronym: IntlString.constant('AIFF'),
      subclassOf: [],
      alias: ['audio/aiff'],
      globs: [
        Glob(pattern: '*.aif', weight: 50, caseSensitive: false),
        Glob(pattern: '*.aiff', weight: 50, caseSensitive: false),
        Glob(pattern: '*.aifc', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 20,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'FORM....AIFF',
              mask: '0xFFFFFFFF00000000FFFFFFFF',
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'FORM....AIFC',
              mask: '0xFFFFFFFF00000000FFFFFFFF',
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'FORM....8SVX',
              mask: '0xFFFFFFFF00000000FFFFFFFF',
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'FORM\x00',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-caf': [
    RegistryEntry(
      mediaType: 'audio/x-caf',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.caf', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'caff\x00\x00',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'caff\x00\x01',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'caff\x00\x02',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'caff@\x00',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'caff\x80\x00',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-dec-basic': [
    RegistryEntry(
      mediaType: 'audio/x-dec-basic',
      subclassOf: [],
      alias: [],
      magic: [
        Magic(
          priority: 20,
          matches: [
            Match.factory(
              type: MatchType.big32,
              offset: '0',
              value: '0x0064732E',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.big32,
                  offset: '12',
                  value: '1',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.big32,
                  offset: '12',
                  value: '2',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.big32,
                  offset: '12',
                  value: '3',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.big32,
                  offset: '12',
                  value: '4',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.big32,
                  offset: '12',
                  value: '5',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.big32,
                  offset: '12',
                  value: '6',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.big32,
                  offset: '12',
                  value: '7',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-dec-adpcm': [
    RegistryEntry(
      mediaType: 'audio/x-dec-adpcm',
      subclassOf: [],
      alias: [],
      magic: [
        Magic(
          priority: 20,
          matches: [
            Match.factory(
              type: MatchType.big32,
              offset: '0',
              value: '0x0064732E',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.big32,
                  offset: '12',
                  value: '23',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-flac': [
    RegistryEntry(
      mediaType: 'audio/x-flac',
      acronym: IntlString.constant('FLAC'),
      subclassOf: [],
      alias: ['audio/flac'],
      globs: [Glob(pattern: '*.flac', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'fLaC',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-mod': [
    RegistryEntry(
      mediaType: 'audio/x-mod',
      acronym: IntlString.constant('MOD'),
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.mod', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'Extended\\ Module:',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '21',
              value: 'BMOD2STM',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '1080',
              value: 'M.K.',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '1080',
              value: 'M!K!',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '1080',
              value: 'FLT4',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '1080',
              value: 'FLT8',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '1080',
              value: '4CHN',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '1080',
              value: '6CHN',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '1080',
              value: '8CHN',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '1080',
              value: 'CD81',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '1080',
              value: 'OKTA',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '1080',
              value: '16CN',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '1080',
              value: '32CN',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'IMPM',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-mpegurl': [
    RegistryEntry(
      mediaType: 'audio/x-mpegurl',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.m3u', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#EXTM3U\r\n',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-ms-wax': [
    RegistryEntry(
      mediaType: 'audio/x-ms-wax',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.wax', weight: 50, caseSensitive: false)],
    ),
  ],
  'audio/x-ms-wma': [
    RegistryEntry(
      mediaType: 'audio/x-ms-wma',
      subclassOf: ['video/x-ms-asf'],
      alias: [],
      globs: [Glob(pattern: '*.wma', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.byte,
              offset: '0:8192',
              value: 'Windows Media Audio',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-pn-realaudio': [
    RegistryEntry(
      mediaType: 'audio/x-pn-realaudio',
      subclassOf: [],
      alias: ['audio/x-realaudio'],
      globs: [
        Glob(pattern: '*.ram', weight: 50, caseSensitive: false),
        Glob(pattern: '*.ra', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.big32,
              offset: '0',
              value: '0x2e7261fd',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-pn-realaudio-plugin': [
    RegistryEntry(
      mediaType: 'audio/x-pn-realaudio-plugin',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.rmp', weight: 50, caseSensitive: false)],
    ),
  ],
  'audio/vnd.wave': [
    RegistryEntry(
      mediaType: 'audio/vnd.wave',
      acronym: IntlString.constant('WAV'),
      subclassOf: [],
      alias: ['audio/x-wav', 'audio/wave', 'audio/wav'],
      globs: [Glob(pattern: '*.wav', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 20,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'RIFF....WAVE',
              mask: '0xFFFFFFFF00000000FFFFFFFF',
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-matroska': [
    RegistryEntry(
      mediaType: 'audio/x-matroska',
      subclassOf: ['application/x-matroska'],
      alias: [],
      globs: [Glob(pattern: '*.mka', weight: 50, caseSensitive: false)],
    ),
  ],
};
