// Copyright 2026 The Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Generated by tool/loader.dart
// ignore_for_file: non_constant_identifier_names,unused_import

import 'package:betto_mediatype_detector/betto_mediatype_detector.dart';
import 'package:betto_common/string.dart';
import 'package:meta/meta.dart';

@internal
final Registry mimeinfoDbModel = {
  'model/e57': [
    RegistryEntry(
      mediaType: 'model/e57',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.e57', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'ASTM-E57',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'model/example': [
    RegistryEntry(mediaType: 'model/example', subclassOf: [], alias: []),
  ],
  'model/iges': [
    RegistryEntry(
      mediaType: 'model/iges',
      subclassOf: [],
      alias: [],
      globs: [
        Glob(pattern: '*.igs', weight: 50, caseSensitive: false),
        Glob(pattern: '*.iges', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'model/mesh': [
    RegistryEntry(
      mediaType: 'model/mesh',
      subclassOf: [],
      alias: [],
      globs: [
        Glob(pattern: '*.msh', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mesh', weight: 50, caseSensitive: false),
        Glob(pattern: '*.silo', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'model/x.stl-ascii': [
    RegistryEntry(
      mediaType: 'model/x.stl-ascii',
      subclassOf: [],
      alias: [],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'solid ',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '7:256',
                  value: 'facet ',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'model/x.stl-binary': [
    RegistryEntry(
      mediaType: 'model/x.stl-binary',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.stl', weight: 50, caseSensitive: false)],
    ),
  ],
  'model/vnd.dwf': [
    RegistryEntry(
      mediaType: 'model/vnd.dwf',
      acronym: IntlString.constant('DWF'),
      subclassOf: [],
      alias: ['drawing/x-dwf'],
      globs: [Glob(pattern: '*.dwf', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '(DWF V',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '8',
                  value: '.',
                  mask: null,
                  minShouldMatch: null,
                  subMatches: [
                    Match.factory(
                      type: MatchType.string,
                      offset: '11',
                      value: ')',
                      mask: null,
                      minShouldMatch: null,
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'model/vnd.dwf;version=6': [
    RegistryEntry(
      mediaType: 'model/vnd.dwf;version=6',
      subclassOf: ['model/vnd.dwf'],
      alias: [],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '(DWF V06.',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '11',
                  value: ')PK',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'model/vnd.dwf;version=5': [
    RegistryEntry(
      mediaType: 'model/vnd.dwf;version=5',
      subclassOf: [],
      alias: [],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '(DWF V00.55)',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'model/vnd.dwf;version=2': [
    RegistryEntry(
      mediaType: 'model/vnd.dwf;version=2',
      subclassOf: [],
      alias: [],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '(DWF V00.22)',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'model/vnd.dwfx+xps': [
    RegistryEntry(
      mediaType: 'model/vnd.dwfx+xps',
      subclassOf: ['application/x-tika-ooxml'],
      alias: [],
      globs: [Glob(pattern: '*.dwfx', weight: 50, caseSensitive: false)],
    ),
  ],
  'model/vnd.flatland.3dml': [
    RegistryEntry(
      mediaType: 'model/vnd.flatland.3dml',
      subclassOf: [],
      alias: [],
    ),
  ],
  'model/vnd.gdl': [
    RegistryEntry(
      mediaType: 'model/vnd.gdl',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.gdl', weight: 50, caseSensitive: false)],
    ),
  ],
  'model/vnd.gs-gdl': [
    RegistryEntry(mediaType: 'model/vnd.gs-gdl', subclassOf: [], alias: []),
  ],
  'model/vnd.gs.gdl': [
    RegistryEntry(mediaType: 'model/vnd.gs.gdl', subclassOf: [], alias: []),
  ],
  'model/vnd.gtw': [
    RegistryEntry(
      mediaType: 'model/vnd.gtw',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.gtw', weight: 50, caseSensitive: false)],
    ),
  ],
  'model/vnd.moml+xml': [
    RegistryEntry(mediaType: 'model/vnd.moml+xml', subclassOf: [], alias: []),
  ],
  'model/vnd.mts': [
    RegistryEntry(
      mediaType: 'model/vnd.mts',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.mts', weight: 50, caseSensitive: false)],
    ),
  ],
  'model/vnd.parasolid.transmit.binary': [
    RegistryEntry(
      mediaType: 'model/vnd.parasolid.transmit.binary',
      subclassOf: [],
      alias: [],
    ),
  ],
  'model/vnd.parasolid.transmit.text': [
    RegistryEntry(
      mediaType: 'model/vnd.parasolid.transmit.text',
      subclassOf: [],
      alias: [],
    ),
  ],
  'model/vnd.vtu': [
    RegistryEntry(
      mediaType: 'model/vnd.vtu',
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.vtu', weight: 50, caseSensitive: false)],
    ),
  ],
  'model/vrml': [
    RegistryEntry(
      mediaType: 'model/vrml',
      subclassOf: [],
      alias: [],
      globs: [
        Glob(pattern: '*.wrl', weight: 50, caseSensitive: false),
        Glob(pattern: '*.vrml', weight: 50, caseSensitive: false),
      ],
    ),
  ],
};
