// Copyright 2026 The Authors. See the AUTHORS file for details.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Helper functions for generating the Tika and Freedesktop mimeinfo
// registry code
library;

import 'dart:io';

import 'package:betto_builder_tools/betto_builder_tools.dart'
    show loadData, dartfmt;
import 'package:betto_mediatype_detector/mediatype_detector.dart';
import 'package:code_builder/code_builder.dart';
import 'package:path/path.dart' as p;
import 'package:xml/xml.dart';

import 'copyright.dart' show loadCopyrightHeader;

final copyrightHeader = loadCopyrightHeader();

void build({
  required String downloadUrl,
  required File dataOutputFile,
  required Directory codeOutputDir,
}) {
  dataOutputFile.parent.create(recursive: true);
  print('Data files will be placed in ${dataOutputFile.absolute.path}');

  codeOutputDir.create(recursive: true);
  print('Code files will be placed in ${codeOutputDir.absolute..path}');

  loadData(dataOutputFile.absolute.path, downloadUrl).then((data) {
    final document = XmlDocument.parse(data);

    buildMimeInfoRegistry(document, codeOutputDir);
  });
}

void buildMimeInfoRegistry(XmlDocument document, Directory outputDir) {
  final entries = document.rootElement.findElements('mime-type');

  // Group entries by their top-level media type (e.g. 'application', 'image')
  final byTopLevel = <String, List<XmlElement>>{};
  for (final entry in entries) {
    var type = entry.getAttribute('type');

    if (type == null) continue;
    final topLevel = type.split('/').first;
    byTopLevel.putIfAbsent(topLevel, () => []).add(entry);
  }

  final generatedFiles = <String>[];

  // Generate a separate file for each top-level media type
  for (final topLevel in byTopLevel.keys) {
    final topLevelEntries = byTopLevel[topLevel]!;
    final sanitizedTopLevel = topLevel.replaceAll('-', '_');
    final dbName =
        'mimeinfoDb${sanitizedTopLevel.substring(0, 1).toUpperCase()}${sanitizedTopLevel.substring(1)}';

    final Map<String, List<String>> listing = {};

    for (final entry in topLevelEntries) {
      final mapped = mapEntry(entry);
      listing[mapped.key] ??= [];
      listing[mapped.key]?.add(mapped.value);
    }

    final library = Library(
      (lib) => lib
        ..comments.addAll(copyrightHeader)
        ..generatedByComment =
            'Generated by tool/loader.dart\n// ignore_for_file: non_constant_identifier_names,unused_import'
        ..directives.addAll([
          Directive.import(
            'package:betto_mediatype_detector/mediatype_detector.dart',
          ),
          Directive.import('package:betto_common/string.dart'),
          Directive.import('package:meta/meta.dart'),
        ])
        ..body.addAll([
          Field(
            (fb) => fb
              ..name = dbName
              ..annotations.add(Reference('internal'))
              ..modifier = FieldModifier.final$
              ..type = Reference('Registry')
              ..assignment = Code(
                '{${[for (final e in listing.entries) "'${e.key}': [${e.value.join(",")}]"].join(',')}}',
              ),
          ),
        ]),
    );

    final fileName = 'mimeinfo_$sanitizedTopLevel.dart';
    generatedFiles.add(fileName);
    File(
      p.join(outputDir.path, fileName),
      //).writeAsStringSync('${library.accept(DartEmitter())}');
    ).writeAsStringSync(dartfmt.format('${library.accept(DartEmitter())}'));
  }

  // Generate the central mimeinfo.dart that aggregates all top-level databases
  final centralLibrary = Library(
    (lib) => lib
      ..comments.addAll(copyrightHeader)
      ..generatedByComment = 'Generated by tool/tika.dart'
      ..directives.addAll([
        Directive.import('package:meta/meta.dart'),
        Directive.import(
          'package:betto_mediatype_detector/mediatype_detector.dart',
        ),
        ...generatedFiles.map((file) => Directive.import(file)),
      ])
      ..body.addAll([
        Field(
          (fb) => fb
            ..name = 'mimeinfoDb'
            ..annotations.add(Reference('internal'))
            ..modifier = FieldModifier.final$
            ..type = Reference('Registry')
            ..assignment = Code(
              // ignore: prefer_interpolation_to_compose_strings
              '{' +
                  byTopLevel.keys
                      .map((topLevel) {
                        final sanitizedTopLevel = topLevel.replaceAll('-', '_');
                        final dbName =
                            'mimeinfoDb${sanitizedTopLevel.substring(0, 1).toUpperCase()}'
                            '${sanitizedTopLevel.substring(1)}';
                        return '...$dbName';
                      })
                      .join(',') +
                  '}',
            ),
        ),
      ]),
  );

  File(p.join(outputDir.path, 'mimeinfo.dart')).writeAsStringSync(
    dartfmt.format('${centralLibrary.accept(DartEmitter())}'),
    //'${centralLibrary.accept(DartEmitter())}',
  );
}

MapEntry<String, String> mapEntry(XmlElement entry) {
  var type = entry.getAttribute('type');
  if (type == null) {
    throw ('Missing type attribute: $entry');
  }

  final key = type;

  final parts = <String>[
    codeMediaType(type),
    codeIcon(entry.getElement('icon')?.getAttribute('name')),
    codeGenericIcon(entry.getElement('generic-icon')?.getAttribute('name')),
    codeComment(getValue(entry, 'comment')),
    codeAcronym(getValue(entry, 'acronym')),
    codeExpandedAcronym(getValue(entry, 'expanded-acronym')),
    codeSubclassMediaType(
      entry
          .findElements('sub-class-of')
          .map((e) => e.getAttribute('type')!)
          .toList(),
    ),
    codeAlias(
      entry.findElements('alias').map((e) => e.getAttribute('type')!).toList(),
    ),
    codeGlobs(entry.findElements('glob')),
    codeMagic(entry.findElements('magic')),
    codeRootXML(entry.findElements('root-XML')),
  ].where((p) => p.isNotEmpty).join(', ');

  return MapEntry(key, 'RegistryEntry($parts)');
}

String codeRootXML(Iterable<XmlElement> rootXMLs) {
  /*
  <!ELEMENT rootXML (rootXML)*>
  <!ATTLIST rootXML namespaceURI CDATA #REQUIRED>
  <!ATTLIST rootXML localName CDATA #REQUIRED>
  */
  final result = <String>[];
  for (var rootXML in rootXMLs) {
    result.add(
      'RootXML('
      'namespaceURI: ${_quote(rootXML.getAttribute('namespaceURI'))},'
      'localName: ${_quote(rootXML.getAttribute('localName'))},'
      ')',
    );
  }
  if (result.isEmpty) return '';
  return 'rootXML: [${result.join(', ')}]';
}

String codeMagic(Iterable<XmlElement> magics) {
  final result = <String>[];
  for (var magic in magics) {
    final matchesStr = codeMatches(magic.findElements('match'));
    result.add(
      'Magic('
      'priority: ${magic.getAttribute('priority') ?? 50},'
      '${matchesStr.isEmpty ? '' : 'matches: $matchesStr,'}'
      ')',
    );
  }
  if (result.isEmpty) return '';
  return 'magic: [${result.join(', ')}]';
}

String codeMatches(Iterable<XmlElement> matches) {
  final result = <String>[];
  for (var match in matches) {
    final type = MatchType.tryParse(match.getAttribute('type') ?? 'byte');
    final submatches = match.findElements('match');
    final subMatchesStr = codeMatches(submatches);

    final msmAttr = match.getAttribute('minShouldMatch');
    final int? minShouldMatch;
    if (msmAttr != null) {
      minShouldMatch = int.tryParse(msmAttr);
    } else {
      minShouldMatch = null;
    }

    result.add(
      'Match.factory('
      // From what I can see, Tika treats `byte` as the default (?)
      'type: MatchType.${type?.name ?? 'byte'},'
      'offset: ${_quote(match.getAttribute('offset') ?? '0')},'
      'value: ${_quote(match.getAttribute('value'))},'
      'mask: ${_quote(match.getAttribute('mask'))},'
      'minShouldMatch: $minShouldMatch'
      '${subMatchesStr.isEmpty ? '' : ', subMatches: $subMatchesStr'}'
      ')',
    );
  }
  if (result.isEmpty) return '';
  return '[${result.join(', ')}]';
}

bool _isSimpleExtension(String pattern) {
  if (pattern.length < 2) return false;
  return pattern.startsWith('*.') &&
      !pattern.substring(2).contains('*') &&
      !pattern.substring(2).contains('?') &&
      !pattern.substring(2).contains('[');
}

String codeGlobs(Iterable<XmlElement> globs) {
  var result = <String>[];
  for (var glob in globs) {
    final pattern = glob.getAttribute('pattern') ?? '';
    final weightStr = glob.getAttribute('weight');
    final weight = weightStr != null ? int.parse(weightStr) : 50;
    var caseSensitive = glob.getAttribute('case-sensitive');

    caseSensitive ??= (!(_isSimpleExtension(pattern) && weight <= 50))
        .toString();

    final args = <String>[
      'pattern: ${_quote(pattern)}',
      'weight: $weight',
      'caseSensitive: $caseSensitive',
    ];

    result.add('Glob(${args.join(', ')})');
  }
  if (result.isEmpty) return '';
  return 'globs: [${result.join(', ')}]';
}

String codeAlias(List<String> types) {
  return 'alias: [${types.map((e) => "'$e'").join(', ')}]';
}

String codeExpandedAcronym(String? expandedAcronym) {
  if (expandedAcronym == null || expandedAcronym.isEmpty) {
    return '';
  }
  return 'expandedAcronym: IntlString.constant(${_quote(expandedAcronym)})';
}

String codeAcronym(String? acronym) {
  if (acronym == null || acronym.isEmpty) {
    return '';
  }
  return 'acronym: IntlString.constant(${_quote(acronym)})';
}

String codeComment(String? comment) {
  if (comment == null || comment.isEmpty) {
    return '';
  }
  return 'comments: [IntlString.constant(${_quote(comment)})]';
}

String codeGenericIcon(String? name) {
  if (name == null) {
    return '';
  }
  final GenericIcon? icon = GenericIcon.tryParse(name);
  if (icon == null) {
    throw ('Invalid generic icon: $name');
  }
  return 'genericIcon: GenericIcon.${icon.name}';
}

String codeIcon(String? name) {
  if (name == null || name.isEmpty) {
    return '';
  }
  return 'icon: IntlString.constant(${_quote(name)})';
}

String codeMediaType(String type, {bool keyOnly = false}) {
  return "mediaType: '$type'";
}

String codeSubclassMediaType(List<String> types) {
  return 'subclassOf: [${types.map((e) => "'$e'").join(', ')}]';
}

String? getValue(XmlElement element, String child) {
  var e = element.getElement(child);
  return e?.innerText.trim();
}

List<String> getStringList(XmlElement element, String child) {
  var e = element.findElements(child);
  return e.map((e) => e.innerText.trim()).toList();
}

String _decodeMagicValue(String s) {
  // The freedesktop XML encodes binary values using C-style escape sequences.
  // Octal escapes may be 1–3 digits (e.g. \0, \07, \012), not just 3.
  return s.replaceAllMapped(
    RegExp(r'\\([bfnrtv\\]|x[0-9a-fA-F]{2}|[0-7]{1,3})'),
    (m) {
      var match = m.group(0)!;
      if (match == r'\\') return r'\';
      if (match == r'\b') return '\b';
      if (match == r'\f') return '\f';
      if (match == r'\n') return '\n';
      if (match == r'\r') return '\r';
      if (match == r'\t') return '\t';
      if (match == r'\v') return '\v';
      if (match.startsWith(r'\x')) {
        return String.fromCharCode(int.parse(match.substring(2), radix: 16));
      }
      if (RegExp(r'\\[0-7]{1,3}').hasMatch(match)) {
        return String.fromCharCode(int.parse(match.substring(1), radix: 8));
      }
      return match;
    },
  );
}

String _quote(String? value) {
  if (value == null) return 'null';
  final decoded = _decodeMagicValue(value);
  final buffer = StringBuffer("'");
  for (var i = 0; i < decoded.length; i++) {
    var char = decoded[i];
    var code = decoded.codeUnitAt(i);
    switch (char) {
      case "'":
        buffer.write(r"\'");
        break;
      case r'\':
        buffer.write(r'\\');
        break;
      case r'$':
        buffer.write(r'\$');
        break;
      case '\n':
        buffer.write(r'\n');
        break;
      case '\r':
        buffer.write(r'\r');
        break;
      case '\t':
        buffer.write(r'\t');
        break;
      case '\b':
        buffer.write(r'\b');
        break;
      case '\f':
        buffer.write(r'\f');
        break;
      case '\v':
        buffer.write(r'\v');
        break;
      default:
        if (code < 0x20 || code >= 0x7F) {
          buffer.write('\\x${code.toRadixString(16).padLeft(2, '0')}');
        } else {
          buffer.write(char);
        }
    }
  }
  buffer.write("'");
  return buffer.toString();
}
