// Copyright 2026 The Authors
//
// Please refer to the AUTHORS file in the base directory for this project.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Generated by tool/loader.dart
// ignore_for_file: non_constant_identifier_names,unused_import

import 'package:betto_mediatype_detector/mediatype_detector.dart';
import 'package:betto_common/string.dart';
import 'package:meta/meta.dart';

@internal
final Registry mimeinfoDbInode = {
  'inode/blockdevice': [
    RegistryEntry(
      mediaType: 'inode/blockdevice',
      comments: [IntlString.constant('Block device')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'inode/chardevice': [
    RegistryEntry(
      mediaType: 'inode/chardevice',
      comments: [IntlString.constant('Character device')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'inode/directory': [
    RegistryEntry(
      mediaType: 'inode/directory',
      genericIcon: GenericIcon.folder,
      comments: [IntlString.constant('Folder')],
      subclassOf: [],
      alias: ['x-directory/normal'],
    ),
  ],
  'inode/fifo': [
    RegistryEntry(
      mediaType: 'inode/fifo',
      comments: [IntlString.constant('Pipe')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'inode/mount-point': [
    RegistryEntry(
      mediaType: 'inode/mount-point',
      comments: [IntlString.constant('Mount point')],
      subclassOf: ['inode/directory'],
      alias: [],
    ),
  ],
  'inode/socket': [
    RegistryEntry(
      mediaType: 'inode/socket',
      comments: [IntlString.constant('Socket')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'inode/symlink': [
    RegistryEntry(
      mediaType: 'inode/symlink',
      comments: [IntlString.constant('Symbolic link')],
      subclassOf: [],
      alias: [],
    ),
  ],
};
