// Copyright 2026 The Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Generated by tool/loader.dart
// ignore_for_file: non_constant_identifier_names,unused_import

import 'package:betto_mediatype_detector/mediatype_detector.dart';
import 'package:betto_common/string.dart';
import 'package:meta/meta.dart';

@internal
final Registry mimeinfoDbAudio = {
  'audio/x-amzxml': [
    RegistryEntry(
      mediaType: 'audio/x-amzxml',
      comments: [IntlString.constant('AmazonMP3 download file')],
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.amz', weight: 50, caseSensitive: false)],
    ),
  ],
  'audio/x-gsm': [
    RegistryEntry(
      mediaType: 'audio/x-gsm',
      comments: [IntlString.constant('GSM 06.10 audio')],
      acronym: IntlString.constant('GSM'),
      expandedAcronym: IntlString.constant(
        'Global System for Mobile communications',
      ),
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.gsm', weight: 50, caseSensitive: false)],
    ),
  ],
  'audio/x-iriver-pla': [
    RegistryEntry(
      mediaType: 'audio/x-iriver-pla',
      comments: [IntlString.constant('iRiver playlist')],
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.pla', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'iriver UMS PLA',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-matroska': [
    RegistryEntry(
      mediaType: 'audio/x-matroska',
      comments: [IntlString.constant('Matroska audio')],
      subclassOf: ['application/x-matroska'],
      alias: [],
      globs: [Glob(pattern: '*.mka', weight: 50, caseSensitive: false)],
    ),
  ],
  'audio/webm': [
    RegistryEntry(
      mediaType: 'audio/webm',
      comments: [IntlString.constant('WebM audio')],
      subclassOf: ['video/webm'],
      alias: [],
    ),
  ],
  'audio/annodex': [
    RegistryEntry(
      mediaType: 'audio/annodex',
      comments: [IntlString.constant('Annodex audio')],
      subclassOf: ['application/annodex'],
      alias: ['audio/x-annodex'],
      globs: [Glob(pattern: '*.axa', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'OggS',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '28',
                  value: 'fishead\x00',
                  mask: null,
                  minShouldMatch: null,
                  subMatches: [
                    Match.factory(
                      type: MatchType.string,
                      offset: '56:512',
                      value: 'CMML\x00\x00\x00\x00',
                      mask: null,
                      minShouldMatch: null,
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/ogg': [
    RegistryEntry(
      mediaType: 'audio/ogg',
      comments: [IntlString.constant('Ogg audio')],
      subclassOf: ['application/ogg'],
      alias: ['audio/x-ogg'],
      globs: [
        Glob(pattern: '*.oga', weight: 50, caseSensitive: false),
        Glob(pattern: '*.ogg', weight: 50, caseSensitive: false),
        Glob(pattern: '*.opus', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'OggS',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-vorbis+ogg': [
    RegistryEntry(
      mediaType: 'audio/x-vorbis+ogg',
      comments: [IntlString.constant('Ogg Vorbis audio')],
      subclassOf: ['audio/ogg'],
      alias: ['audio/vorbis', 'audio/x-vorbis'],
      globs: [
        Glob(pattern: '*.oga', weight: 50, caseSensitive: false),
        Glob(pattern: '*.ogg', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 80,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'OggS',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '28',
                  value: '\x01vorbis',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-flac+ogg': [
    RegistryEntry(
      mediaType: 'audio/x-flac+ogg',
      comments: [IntlString.constant('Ogg FLAC audio')],
      subclassOf: ['audio/ogg'],
      alias: ['audio/x-oggflac'],
      globs: [
        Glob(pattern: '*.oga', weight: 50, caseSensitive: false),
        Glob(pattern: '*.ogg', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 80,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'OggS',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '28',
                  value: 'fLaC',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'OggS',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '28',
                  value: '\x7fFLAC',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-opus+ogg': [
    RegistryEntry(
      mediaType: 'audio/x-opus+ogg',
      comments: [IntlString.constant('Opus audio')],
      subclassOf: ['audio/ogg'],
      alias: [],
      globs: [Glob(pattern: '*.opus', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 80,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'OggS',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '28',
                  value: 'OpusHead',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-speex+ogg': [
    RegistryEntry(
      mediaType: 'audio/x-speex+ogg',
      comments: [IntlString.constant('Ogg Speex audio')],
      subclassOf: ['audio/ogg'],
      alias: [],
      globs: [
        Glob(pattern: '*.oga', weight: 50, caseSensitive: false),
        Glob(pattern: '*.ogg', weight: 50, caseSensitive: false),
        Glob(pattern: '*.spx', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 80,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'OggS',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '28',
                  value: 'Speex  ',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-speex': [
    RegistryEntry(
      mediaType: 'audio/x-speex',
      comments: [IntlString.constant('Speex audio')],
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.spx', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'Speex',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-xmf': [
    RegistryEntry(
      mediaType: 'audio/x-xmf',
      comments: [IntlString.constant('XMF audio')],
      acronym: IntlString.constant('XMF'),
      expandedAcronym: IntlString.constant('eXtensible Music Format'),
      subclassOf: [],
      alias: ['audio/xmf'],
      globs: [Glob(pattern: '*.xmf', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'XMF_',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/mobile-xmf': [
    RegistryEntry(
      mediaType: 'audio/mobile-xmf',
      comments: [IntlString.constant('Mobile XMF audio')],
      acronym: IntlString.constant('XMF'),
      expandedAcronym: IntlString.constant('eXtensible Music Format'),
      subclassOf: [],
      alias: ['audio/vnd.nokia.mobile-xmf'],
      globs: [Glob(pattern: '*.mxmf', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'XMF_2.00\x00\x00\x00\x02',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/ac3': [
    RegistryEntry(
      mediaType: 'audio/ac3',
      comments: [IntlString.constant('Dolby Digital audio')],
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.ac3', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.big16,
              offset: '0',
              value: '0x0b77',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/vnd.dts': [
    RegistryEntry(
      mediaType: 'audio/vnd.dts',
      comments: [IntlString.constant('DTS audio')],
      acronym: IntlString.constant('DTS'),
      expandedAcronym: IntlString.constant('Digital Theater Systems'),
      subclassOf: [],
      alias: ['audio/x-dts'],
      globs: [Glob(pattern: '*.dts', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.big32,
              offset: '0',
              value: '0x7FFE8001',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.little32,
              offset: '0',
              value: '0xFE7F0180',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.big32,
              offset: '0',
              value: '0x1FFFE800',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.little32,
              offset: '0',
              value: '0xFF1F00E8',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/vnd.dts.hd': [
    RegistryEntry(
      mediaType: 'audio/vnd.dts.hd',
      comments: [IntlString.constant('DTS-HD audio')],
      acronym: IntlString.constant('DTS-HD'),
      expandedAcronym: IntlString.constant(
        'Digital Theater Systems High Definition',
      ),
      subclassOf: ['audio/vnd.dts'],
      alias: ['audio/x-dtshd'],
      globs: [Glob(pattern: '*.dtshd', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 60,
          matches: [
            Match.factory(
              type: MatchType.big32,
              offset: '0',
              value: '0x7FFE8001',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.big32,
                  offset: '4:18725',
                  value: '0x64582025',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/AMR': [
    RegistryEntry(
      mediaType: 'audio/AMR',
      comments: [IntlString.constant('AMR audio')],
      acronym: IntlString.constant('AMR'),
      expandedAcronym: IntlString.constant('Adaptive Multi-Rate'),
      subclassOf: [],
      alias: ['audio/amr-encrypted'],
      globs: [Glob(pattern: '*.amr', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#!AMR\n',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#!AMR_MC1.0\n',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/AMR-WB': [
    RegistryEntry(
      mediaType: 'audio/AMR-WB',
      comments: [IntlString.constant('AMR-WB audio')],
      acronym: IntlString.constant('AMR-WB'),
      expandedAcronym: IntlString.constant('Adaptive Multi-Rate Wideband'),
      subclassOf: [],
      alias: ['audio/amr-wb-encrypted'],
      globs: [Glob(pattern: '*.awb', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#!AMR-WB\n',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#!AMR-WB_MC1.0\n',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/basic': [
    RegistryEntry(
      mediaType: 'audio/basic',
      comments: [IntlString.constant('ULAW (Sun) audio')],
      subclassOf: [],
      alias: [],
      globs: [
        Glob(pattern: '*.au', weight: 50, caseSensitive: false),
        Glob(pattern: '*.snd', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 40,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '.snd',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/prs.sid': [
    RegistryEntry(
      mediaType: 'audio/prs.sid',
      comments: [IntlString.constant('Commodore 64 audio')],
      subclassOf: [],
      alias: [],
      globs: [
        Glob(pattern: '*.sid', weight: 50, caseSensitive: false),
        Glob(pattern: '*.psid', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'PSID',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-adpcm': [
    RegistryEntry(
      mediaType: 'audio/x-adpcm',
      comments: [IntlString.constant('PCM audio')],
      acronym: IntlString.constant('PCM'),
      expandedAcronym: IntlString.constant('Pulse-code Modulation'),
      subclassOf: [],
      alias: [],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '.snd',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.big32,
                  offset: '12',
                  value: '23',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
            Match.factory(
              type: MatchType.little32,
              offset: '0',
              value: '0x0064732E',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.little32,
                  offset: '12',
                  value: '1',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.little32,
                  offset: '12',
                  value: '2',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.little32,
                  offset: '12',
                  value: '3',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.little32,
                  offset: '12',
                  value: '4',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.little32,
                  offset: '12',
                  value: '5',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.little32,
                  offset: '12',
                  value: '6',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.little32,
                  offset: '12',
                  value: '7',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.little32,
                  offset: '12',
                  value: '23',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-aifc': [
    RegistryEntry(
      mediaType: 'audio/x-aifc',
      comments: [IntlString.constant('AIFC audio')],
      acronym: IntlString.constant('AIFC'),
      expandedAcronym: IntlString.constant(
        'Audio Interchange File format Compressed',
      ),
      subclassOf: ['application/x-iff'],
      alias: ['audio/x-aiffc'],
      globs: [
        Glob(pattern: '*.aifc', weight: 50, caseSensitive: false),
        Glob(pattern: '*.aiffc', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '8',
              value: 'AIFC',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-aiff': [
    RegistryEntry(
      mediaType: 'audio/x-aiff',
      comments: [IntlString.constant('AIFF/Amiga/Mac audio')],
      acronym: IntlString.constant('AIFF'),
      expandedAcronym: IntlString.constant('Audio Interchange File Format'),
      subclassOf: ['application/x-iff'],
      alias: [],
      globs: [
        Glob(pattern: '*.aiff', weight: 50, caseSensitive: false),
        Glob(pattern: '*.aif', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '8',
              value: 'AIFF',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '8',
              value: '8SVX',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-ape': [
    RegistryEntry(
      mediaType: 'audio/x-ape',
      comments: [IntlString.constant('Monkey\'s audio')],
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.ape', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'MAC ',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-pn-audibleaudio': [
    RegistryEntry(
      mediaType: 'audio/x-pn-audibleaudio',
      comments: [IntlString.constant('Audible.Com audio')],
      subclassOf: [],
      alias: ['audio/vnd.audible'],
      globs: [Glob(pattern: '*.aa', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.big32,
              offset: '4',
              value: '1469084982',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/vnd.audible.aax': [
    RegistryEntry(
      mediaType: 'audio/vnd.audible.aax',
      comments: [IntlString.constant('Audible Enhanced audio')],
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.aax', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftypaax ',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/vnd.audible.aaxc': [
    RegistryEntry(
      mediaType: 'audio/vnd.audible.aaxc',
      comments: [IntlString.constant('Audible Enhanced audio')],
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.aaxc', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftypaaxc',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-dff': [
    RegistryEntry(
      mediaType: 'audio/x-dff',
      comments: [IntlString.constant('DSDIFF audio')],
      acronym: IntlString.constant('DSDIFF'),
      expandedAcronym: IntlString.constant(
        'Direct Stream Digital Interchange File Format',
      ),
      subclassOf: [],
      alias: ['audio/dff'],
      globs: [Glob(pattern: '*.dff', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'FRM8',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '12',
                  value: 'DSD ',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-dsf': [
    RegistryEntry(
      mediaType: 'audio/x-dsf',
      comments: [IntlString.constant('DSF audio')],
      acronym: IntlString.constant('DSF'),
      expandedAcronym: IntlString.constant('Direct stream digital Stream File'),
      subclassOf: [],
      alias: ['audio/dsf', 'audio/x-dsd', 'audio/dsd'],
      globs: [Glob(pattern: '*.dsf', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'DSD ',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '28',
                  value: 'fmt ',
                  mask: null,
                  minShouldMatch: null,
                  subMatches: [
                    Match.factory(
                      type: MatchType.string,
                      offset: '80',
                      value: 'data',
                      mask: null,
                      minShouldMatch: null,
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-it': [
    RegistryEntry(
      mediaType: 'audio/x-it',
      comments: [IntlString.constant('Impulse Tracker audio')],
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.it', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'IMPM',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/flac': [
    RegistryEntry(
      mediaType: 'audio/flac',
      comments: [IntlString.constant('FLAC audio')],
      acronym: IntlString.constant('FLAC'),
      expandedAcronym: IntlString.constant('Free Lossless Audio Codec'),
      subclassOf: [],
      alias: ['audio/x-flac'],
      globs: [Glob(pattern: '*.flac', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'fLaC',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-tak': [
    RegistryEntry(
      mediaType: 'audio/x-tak',
      comments: [IntlString.constant('TAK audio')],
      acronym: IntlString.constant('TAK'),
      expandedAcronym: IntlString.constant('Tom\'s lossless Audio Kompressor'),
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.tak', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'tBaK',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-wavpack': [
    RegistryEntry(
      mediaType: 'audio/x-wavpack',
      comments: [IntlString.constant('WavPack audio')],
      subclassOf: [],
      alias: [],
      globs: [
        Glob(pattern: '*.wv', weight: 50, caseSensitive: false),
        Glob(pattern: '*.wvp', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'wvpk',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-wavpack-correction': [
    RegistryEntry(
      mediaType: 'audio/x-wavpack-correction',
      comments: [IntlString.constant('WavPack audio correction file')],
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.wvc', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'wvpk',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/midi': [
    RegistryEntry(
      mediaType: 'audio/midi',
      comments: [IntlString.constant('MIDI audio')],
      acronym: IntlString.constant('MIDI'),
      expandedAcronym: IntlString.constant(
        'Musical Instrument Digital Interface',
      ),
      subclassOf: [],
      alias: ['audio/x-midi'],
      globs: [
        Glob(pattern: '*.mid', weight: 50, caseSensitive: false),
        Glob(pattern: '*.midi', weight: 50, caseSensitive: false),
        Glob(pattern: '*.kar', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'MThd',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-mo3': [
    RegistryEntry(
      mediaType: 'audio/x-mo3',
      comments: [IntlString.constant('Compressed Tracker audio')],
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.mo3', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'MO3',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/aac': [
    RegistryEntry(
      mediaType: 'audio/aac',
      comments: [IntlString.constant('AAC audio')],
      acronym: IntlString.constant('AAC'),
      expandedAcronym: IntlString.constant('Advanced Audio Coding'),
      subclassOf: [],
      alias: ['audio/x-aac'],
      globs: [
        Glob(pattern: '*.aac', weight: 50, caseSensitive: false),
        Glob(pattern: '*.adts', weight: 50, caseSensitive: false),
        Glob(pattern: '*.ass', weight: 10, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'ADIF',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.big16,
              offset: '0',
              value: '0xFFF0',
              mask: '0xFFF6',
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/usac': [
    RegistryEntry(
      mediaType: 'audio/usac',
      comments: [IntlString.constant('USAC audio')],
      acronym: IntlString.constant('USAC'),
      expandedAcronym: IntlString.constant('Unified Speech and Audio Coding'),
      subclassOf: [],
      alias: [],
      globs: [
        Glob(pattern: '*.loas', weight: 50, caseSensitive: false),
        Glob(pattern: '*.xhe', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'audio/mp4': [
    RegistryEntry(
      mediaType: 'audio/mp4',
      comments: [IntlString.constant('MPEG-4 audio')],
      subclassOf: [],
      alias: ['audio/x-m4a', 'audio/m4a'],
      globs: [
        Glob(pattern: '*.m4a', weight: 50, caseSensitive: false),
        Glob(pattern: '*.f4a', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftypM4A',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-m4r': [
    RegistryEntry(
      mediaType: 'audio/x-m4r',
      comments: [IntlString.constant('MPEG-4 ringtone')],
      subclassOf: ['video/mp4'],
      alias: [],
      globs: [Glob(pattern: '*.m4r', weight: 50, caseSensitive: false)],
    ),
  ],
  'audio/x-m4b': [
    RegistryEntry(
      mediaType: 'audio/x-m4b',
      comments: [IntlString.constant('MPEG-4 audio book')],
      subclassOf: ['audio/mp4'],
      alias: [],
      globs: [
        Glob(pattern: '*.m4b', weight: 50, caseSensitive: false),
        Glob(pattern: '*.f4b', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftypM4B',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-mod': [
    RegistryEntry(
      mediaType: 'audio/x-mod',
      comments: [IntlString.constant('Amiga SoundTracker audio')],
      subclassOf: [],
      alias: [],
      globs: [
        Glob(pattern: '*.mod', weight: 50, caseSensitive: false),
        Glob(pattern: '*.ult', weight: 50, caseSensitive: false),
        Glob(pattern: '*.uni', weight: 50, caseSensitive: false),
        Glob(pattern: '*.m15', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mtm', weight: 50, caseSensitive: false),
        Glob(pattern: '*.669', weight: 50, caseSensitive: false),
        Glob(pattern: '*.med', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 40,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'MTM',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'MMD0',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'MMD1',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.byte,
              offset: '112',
              value: '0x0',
              mask: '0x80',
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '0',
                  value: 'if',
                  mask: null,
                  minShouldMatch: null,
                  subMatches: [
                    Match.factory(
                      type: MatchType.byte,
                      offset: '368',
                      value: '0x0',
                      mask: '0xe0',
                      minShouldMatch: null,
                      subMatches: [
                        Match.factory(
                          type: MatchType.byte,
                          offset: '110',
                          value: '0x0',
                          mask: '0xc0',
                          minShouldMatch: null,
                          subMatches: [
                            Match.factory(
                              type: MatchType.byte,
                              offset: '111',
                              value: '0x0',
                              mask: '0x80',
                              minShouldMatch: null,
                            ),
                            Match.factory(
                              type: MatchType.byte,
                              offset: '111',
                              value: '0x80',
                              mask: null,
                              minShouldMatch: null,
                            ),
                          ],
                        ),
                        Match.factory(
                          type: MatchType.byte,
                          offset: '110',
                          value: '0x40',
                          mask: null,
                          minShouldMatch: null,
                          subMatches: [
                            Match.factory(
                              type: MatchType.byte,
                              offset: '111',
                              value: '0x0',
                              mask: '0x80',
                              minShouldMatch: null,
                            ),
                            Match.factory(
                              type: MatchType.byte,
                              offset: '111',
                              value: '0x80',
                              mask: null,
                              minShouldMatch: null,
                            ),
                          ],
                        ),
                      ],
                    ),
                    Match.factory(
                      type: MatchType.byte,
                      offset: '368',
                      value: '0x20',
                      mask: null,
                      minShouldMatch: null,
                      subMatches: [
                        Match.factory(
                          type: MatchType.byte,
                          offset: '110',
                          value: '0x0',
                          mask: '0xc0',
                          minShouldMatch: null,
                          subMatches: [
                            Match.factory(
                              type: MatchType.byte,
                              offset: '111',
                              value: '0x0',
                              mask: '0x80',
                              minShouldMatch: null,
                            ),
                            Match.factory(
                              type: MatchType.byte,
                              offset: '111',
                              value: '0x80',
                              mask: null,
                              minShouldMatch: null,
                            ),
                          ],
                        ),
                        Match.factory(
                          type: MatchType.byte,
                          offset: '110',
                          value: '0x40',
                          mask: null,
                          minShouldMatch: null,
                          subMatches: [
                            Match.factory(
                              type: MatchType.byte,
                              offset: '111',
                              value: '0x0',
                              mask: '0x80',
                              minShouldMatch: null,
                            ),
                            Match.factory(
                              type: MatchType.byte,
                              offset: '111',
                              value: '0x80',
                              mask: null,
                              minShouldMatch: null,
                            ),
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '0',
                  value: 'JN',
                  mask: null,
                  minShouldMatch: null,
                  subMatches: [
                    Match.factory(
                      type: MatchType.byte,
                      offset: '368',
                      value: '0x0',
                      mask: '0xe0',
                      minShouldMatch: null,
                      subMatches: [
                        Match.factory(
                          type: MatchType.byte,
                          offset: '110',
                          value: '0x0',
                          mask: '0xc0',
                          minShouldMatch: null,
                          subMatches: [
                            Match.factory(
                              type: MatchType.byte,
                              offset: '111',
                              value: '0x0',
                              mask: '0x80',
                              minShouldMatch: null,
                            ),
                            Match.factory(
                              type: MatchType.byte,
                              offset: '111',
                              value: '0x80',
                              mask: null,
                              minShouldMatch: null,
                            ),
                          ],
                        ),
                      ],
                    ),
                    Match.factory(
                      type: MatchType.byte,
                      offset: '368',
                      value: '0x20',
                      mask: null,
                      minShouldMatch: null,
                      subMatches: [
                        Match.factory(
                          type: MatchType.byte,
                          offset: '110',
                          value: '0x40',
                          mask: null,
                          minShouldMatch: null,
                          subMatches: [
                            Match.factory(
                              type: MatchType.byte,
                              offset: '111',
                              value: '0x0',
                              mask: '0x80',
                              minShouldMatch: null,
                            ),
                            Match.factory(
                              type: MatchType.byte,
                              offset: '111',
                              value: '0x80',
                              mask: null,
                              minShouldMatch: null,
                            ),
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'MAS_UTrack_V00',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '1080',
              value: 'M.K.',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '1080',
              value: 'M!K!',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/mp2': [
    RegistryEntry(
      mediaType: 'audio/mp2',
      comments: [IntlString.constant('MP2 audio')],
      subclassOf: [],
      alias: ['audio/x-mp2'],
      globs: [Glob(pattern: '*.mp2', weight: 50, caseSensitive: false)],
    ),
  ],
  'audio/mpeg': [
    RegistryEntry(
      mediaType: 'audio/mpeg',
      comments: [IntlString.constant('MP3 audio')],
      subclassOf: [],
      alias: ['audio/x-mp3', 'audio/x-mpg', 'audio/x-mpeg', 'audio/mp3'],
      globs: [
        Glob(pattern: '*.mp3', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mpga', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.big16,
              offset: '0',
              value: '0xfffa',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.big16,
              offset: '0',
              value: '0xfffb',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.big16,
              offset: '0',
              value: '0xfff3',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.big16,
              offset: '0',
              value: '0xfff2',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.big16,
              offset: '0',
              value: '0xffe3',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.big16,
              offset: '0',
              value: '0xffe2',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'ID3',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-mpegurl': [
    RegistryEntry(
      mediaType: 'audio/x-mpegurl',
      comments: [IntlString.constant('Media playlist')],
      subclassOf: ['text/plain'],
      alias: [
        'audio/mpegurl',
        'application/m3u',
        'audio/x-mp3-playlist',
        'audio/m3u',
        'audio/x-m3u',
      ],
      globs: [
        Glob(pattern: '*.m3u', weight: 50, caseSensitive: false),
        Glob(pattern: '*.m3u8', weight: 50, caseSensitive: false),
        Glob(pattern: '*.vlc', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#EXTM3U',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-ms-asx': [
    RegistryEntry(
      mediaType: 'audio/x-ms-asx',
      comments: [IntlString.constant('Microsoft ASX playlist')],
      subclassOf: [],
      alias: [
        'video/x-ms-wvx',
        'video/x-ms-wax',
        'video/x-ms-wmx',
        'application/x-ms-asx',
      ],
      globs: [
        Glob(pattern: '*.asx', weight: 50, caseSensitive: false),
        Glob(pattern: '*.wax', weight: 50, caseSensitive: false),
        Glob(pattern: '*.wvx', weight: 50, caseSensitive: false),
        Glob(pattern: '*.wmx', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 51,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'ASF ',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0:64',
              value: '<ASX',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0:64',
              value: '<asx',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0:64',
              value: '<Asx',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-psf': [
    RegistryEntry(
      mediaType: 'audio/x-psf',
      comments: [IntlString.constant('PSF audio')],
      acronym: IntlString.constant('PSF'),
      expandedAcronym: IntlString.constant('Portable Sound Format'),
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.psf', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'PSF',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-minipsf': [
    RegistryEntry(
      mediaType: 'audio/x-minipsf',
      comments: [IntlString.constant('MiniPSF audio')],
      acronym: IntlString.constant('MiniPSF'),
      expandedAcronym: IntlString.constant('Miniature Portable Sound Format'),
      subclassOf: ['audio/x-psf'],
      alias: [],
      globs: [Glob(pattern: '*.minipsf', weight: 50, caseSensitive: false)],
    ),
  ],
  'audio/x-psflib': [
    RegistryEntry(
      mediaType: 'audio/x-psflib',
      comments: [IntlString.constant('PSFlib audio library')],
      acronym: IntlString.constant('PSFlib'),
      expandedAcronym: IntlString.constant('Portable Sound Format Library'),
      subclassOf: ['audio/x-psf'],
      alias: [],
      globs: [Glob(pattern: '*.psflib', weight: 50, caseSensitive: false)],
    ),
  ],
  'audio/x-ms-wma': [
    RegistryEntry(
      mediaType: 'audio/x-ms-wma',
      comments: [IntlString.constant('Windows Media audio')],
      subclassOf: ['application/vnd.ms-asf'],
      alias: ['audio/wma'],
      globs: [Glob(pattern: '*.wma', weight: 50, caseSensitive: false)],
    ),
  ],
  'audio/x-musepack': [
    RegistryEntry(
      mediaType: 'audio/x-musepack',
      comments: [IntlString.constant('Musepack audio')],
      subclassOf: [],
      alias: [],
      globs: [
        Glob(pattern: '*.mpc', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mpp', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mp+', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'MP+',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'MPCK',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/vnd.rn-realaudio': [
    RegistryEntry(
      mediaType: 'audio/vnd.rn-realaudio',
      comments: [IntlString.constant('RealAudio document')],
      subclassOf: [],
      alias: ['audio/x-pn-realaudio', 'audio/vnd.m-realaudio'],
      globs: [
        Glob(pattern: '*.ra', weight: 50, caseSensitive: false),
        Glob(pattern: '*.rax', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'audio/x-riff': [
    RegistryEntry(
      mediaType: 'audio/x-riff',
      comments: [IntlString.constant('RIFF audio')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'audio/x-s3m': [
    RegistryEntry(
      mediaType: 'audio/x-s3m',
      comments: [IntlString.constant('Scream Tracker 3 audio')],
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.s3m', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '44',
              value: 'SCRM',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-scpls': [
    RegistryEntry(
      mediaType: 'audio/x-scpls',
      comments: [IntlString.constant('MP3 ShoutCast playlist')],
      subclassOf: [],
      alias: ['application/pls', 'audio/scpls'],
      globs: [Glob(pattern: '*.pls', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '[playlist]',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '[Playlist]',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '[PLAYLIST]',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-stm': [
    RegistryEntry(
      mediaType: 'audio/x-stm',
      comments: [IntlString.constant('Scream Tracker audio')],
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.stm', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '20',
              value: '!Scream!\x1a',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '20',
              value: '!SCREAM!\x1a',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '20',
              value: 'BMOD2STM\x1a',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-voc': [
    RegistryEntry(
      mediaType: 'audio/x-voc',
      comments: [IntlString.constant('VOC audio')],
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.voc', weight: 50, caseSensitive: false)],
    ),
  ],
  'audio/vnd.wave': [
    RegistryEntry(
      mediaType: 'audio/vnd.wave',
      comments: [IntlString.constant('WAV audio')],
      subclassOf: ['application/x-riff'],
      alias: ['audio/wav', 'audio/x-wav'],
      globs: [Glob(pattern: '*.wav', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '8',
              value: 'WAVE',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '8',
              value: 'WAV ',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-xi': [
    RegistryEntry(
      mediaType: 'audio/x-xi',
      comments: [IntlString.constant('FastTracker II instrument')],
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.xi', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'Extended Instrument:',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-xm': [
    RegistryEntry(
      mediaType: 'audio/x-xm',
      comments: [IntlString.constant('FastTracker II audio')],
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.xm', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'Extended Module:',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'audio/x-tta': [
    RegistryEntry(
      mediaType: 'audio/x-tta',
      comments: [IntlString.constant('TrueAudio audio')],
      subclassOf: [],
      alias: ['audio/tta'],
      globs: [Glob(pattern: '*.tta', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'TTA1',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
};
