// Copyright 2026 The Authors
//
// Please refer to the AUTHORS file in the base directory for this project.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Generated by tool/loader.dart
// ignore_for_file: non_constant_identifier_names,unused_import

import 'package:betto_mediatype_detector/mediatype_detector.dart';
import 'package:betto_common/string.dart';
import 'package:meta/meta.dart';

@internal
final Registry mimeinfoDbFont = {
  'font/woff': [
    RegistryEntry(
      mediaType: 'font/woff',
      genericIcon: GenericIcon.fontXGeneric,
      comments: [IntlString.constant('WOFF font')],
      acronym: IntlString.constant('WOFF'),
      expandedAcronym: IntlString.constant('Web Open Font Format'),
      subclassOf: [],
      alias: ['application/font-woff'],
      globs: [Glob(pattern: '*.woff', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.big32,
              offset: '0',
              value: '0x774f4646',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'font/woff2': [
    RegistryEntry(
      mediaType: 'font/woff2',
      genericIcon: GenericIcon.fontXGeneric,
      comments: [IntlString.constant('WOFF2 font')],
      acronym: IntlString.constant('WOFF2'),
      expandedAcronym: IntlString.constant('Web Open Font Format 2.0'),
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.woff2', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.big32,
              offset: '0',
              value: '0x774f4632',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'font/otf': [
    RegistryEntry(
      mediaType: 'font/otf',
      genericIcon: GenericIcon.fontXGeneric,
      comments: [IntlString.constant('OpenType font')],
      subclassOf: ['font/ttf'],
      alias: ['application/x-font-otf'],
      globs: [Glob(pattern: '*.otf', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'OTTO',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'font/ttf': [
    RegistryEntry(
      mediaType: 'font/ttf',
      genericIcon: GenericIcon.fontXGeneric,
      comments: [IntlString.constant('TrueType font')],
      subclassOf: [],
      alias: ['application/x-font-ttf'],
      globs: [Glob(pattern: '*.ttf', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'FFIL',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '65',
              value: 'FFIL',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '\x00\x01\x00\x00\x00',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'font/collection': [
    RegistryEntry(
      mediaType: 'font/collection',
      genericIcon: GenericIcon.fontXGeneric,
      comments: [IntlString.constant('Font collection')],
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.ttc', weight: 50, caseSensitive: false)],
    ),
  ],
};
