// Copyright 2026 The Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Generated by tool/loader.dart
// ignore_for_file: non_constant_identifier_names,unused_import

import 'package:betto_mediatype_detector/mediatype_detector.dart';
import 'package:betto_common/string.dart';
import 'package:meta/meta.dart';

@internal
final Registry mimeinfoDbMessage = {
  'message/delivery-status': [
    RegistryEntry(
      mediaType: 'message/delivery-status',
      genericIcon: GenericIcon.textXGeneric,
      comments: [IntlString.constant('Mail delivery report')],
      subclassOf: ['text/plain'],
      alias: [],
    ),
  ],
  'message/disposition-notification': [
    RegistryEntry(
      mediaType: 'message/disposition-notification',
      genericIcon: GenericIcon.textXGeneric,
      comments: [IntlString.constant('Mail disposition report')],
      subclassOf: ['text/plain'],
      alias: [],
    ),
  ],
  'message/external-body': [
    RegistryEntry(
      mediaType: 'message/external-body',
      genericIcon: GenericIcon.textXGeneric,
      comments: [IntlString.constant('Reference to remote file')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'message/news': [
    RegistryEntry(
      mediaType: 'message/news',
      genericIcon: GenericIcon.textXGeneric,
      comments: [IntlString.constant('Usenet news message')],
      subclassOf: ['text/plain'],
      alias: [],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'Article',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'Path:',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'Xref:',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'message/partial': [
    RegistryEntry(
      mediaType: 'message/partial',
      genericIcon: GenericIcon.textXGeneric,
      comments: [IntlString.constant('Partial email message')],
      subclassOf: ['text/plain'],
      alias: [],
    ),
  ],
  'message/rfc822': [
    RegistryEntry(
      mediaType: 'message/rfc822',
      genericIcon: GenericIcon.textXGeneric,
      comments: [IntlString.constant('Email message')],
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.eml', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#! rnews',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'Content-Type:',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'Forward to',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'From:',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'N#! rnews',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'Pipe to',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'Received:',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'Relay-Version:',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'Return-Path:',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'Return-path:',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'Subject: ',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'To:',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'message/x-gnu-rmail': [
    RegistryEntry(
      mediaType: 'message/x-gnu-rmail',
      genericIcon: GenericIcon.textXGeneric,
      comments: [IntlString.constant('GNU mail message')],
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: 'RMAIL', weight: 50, caseSensitive: true)],
    ),
  ],
};
