// Copyright 2026 The Authors
//
// Please refer to the AUTHORS file in the base directory for this project.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Generated by tool/loader.dart
// ignore_for_file: non_constant_identifier_names,unused_import

import 'package:betto_mediatype_detector/mediatype_detector.dart';
import 'package:betto_common/string.dart';
import 'package:meta/meta.dart';

@internal
final Registry mimeinfoDbX_content = {
  'x-content/image-dcf': [
    RegistryEntry(
      mediaType: 'x-content/image-dcf',
      comments: [IntlString.constant('Digital photos')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'x-content/video-vcd': [
    RegistryEntry(
      mediaType: 'x-content/video-vcd',
      comments: [IntlString.constant('Video CD')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'x-content/video-svcd': [
    RegistryEntry(
      mediaType: 'x-content/video-svcd',
      comments: [IntlString.constant('Super Video CD')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'x-content/video-dvd': [
    RegistryEntry(
      mediaType: 'x-content/video-dvd',
      comments: [IntlString.constant('Video DVD')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'x-content/audio-cdda': [
    RegistryEntry(
      mediaType: 'x-content/audio-cdda',
      comments: [IntlString.constant('Audio CD')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'x-content/blank-cd': [
    RegistryEntry(
      mediaType: 'x-content/blank-cd',
      comments: [IntlString.constant('Blank CD disc')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'x-content/blank-dvd': [
    RegistryEntry(
      mediaType: 'x-content/blank-dvd',
      comments: [IntlString.constant('Blank DVD disc')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'x-content/blank-bd': [
    RegistryEntry(
      mediaType: 'x-content/blank-bd',
      comments: [IntlString.constant('Blank Blu-ray disc')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'x-content/blank-hddvd': [
    RegistryEntry(
      mediaType: 'x-content/blank-hddvd',
      comments: [IntlString.constant('Blank HD DVD disc')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'x-content/audio-dvd': [
    RegistryEntry(
      mediaType: 'x-content/audio-dvd',
      comments: [IntlString.constant('Audio DVD')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'x-content/video-bluray': [
    RegistryEntry(
      mediaType: 'x-content/video-bluray',
      comments: [IntlString.constant('Blu-ray video disc')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'x-content/video-hddvd': [
    RegistryEntry(
      mediaType: 'x-content/video-hddvd',
      comments: [IntlString.constant('HD DVD video disc')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'x-content/ebook-reader': [
    RegistryEntry(
      mediaType: 'x-content/ebook-reader',
      comments: [IntlString.constant('E-book reader')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'x-content/image-picturecd': [
    RegistryEntry(
      mediaType: 'x-content/image-picturecd',
      comments: [IntlString.constant('Picture CD')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'x-content/audio-player': [
    RegistryEntry(
      mediaType: 'x-content/audio-player',
      comments: [IntlString.constant('Portable audio player')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'x-content/ostree-repository': [
    RegistryEntry(
      mediaType: 'x-content/ostree-repository',
      comments: [IntlString.constant('OSTree software updates')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'x-content/software': [
    RegistryEntry(
      mediaType: 'x-content/software',
      comments: [IntlString.constant('Software')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'x-content/unix-software': [
    RegistryEntry(
      mediaType: 'x-content/unix-software',
      comments: [IntlString.constant('UNIX software')],
      subclassOf: ['x-content/software'],
      alias: [],
    ),
  ],
  'x-content/win32-software': [
    RegistryEntry(
      mediaType: 'x-content/win32-software',
      comments: [IntlString.constant('Windows software')],
      subclassOf: ['x-content/software'],
      alias: [],
    ),
  ],
};
