// Copyright 2026 The Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Generated by tool/loader.dart
// ignore_for_file: non_constant_identifier_names,unused_import

import 'package:betto_mediatype_detector/betto_mediatype_detector.dart';
import 'package:betto_common/string.dart';
import 'package:meta/meta.dart';

@internal
final Registry mimeinfoDbModel = {
  'model/iges': [
    RegistryEntry(
      mediaType: 'model/iges',
      genericIcon: GenericIcon.xOfficeDocument,
      comments: [IntlString.constant('IGES document')],
      acronym: IntlString.constant('IGES'),
      expandedAcronym: IntlString.constant(
        'Initial Graphics Exchange Specification',
      ),
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: '*.igs', weight: 50, caseSensitive: false),
        Glob(pattern: '*.iges', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '72',
              value: 'S      1\n',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '72',
              value: 'S0000001\n',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'model/gltf-binary': [
    RegistryEntry(
      mediaType: 'model/gltf-binary',
      genericIcon: GenericIcon.imageXGeneric,
      comments: [IntlString.constant('glTF model')],
      acronym: IntlString.constant('glTF'),
      expandedAcronym: IntlString.constant('GL Transmission Format'),
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.glb', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'glTF',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'model/gltf+json': [
    RegistryEntry(
      mediaType: 'model/gltf+json',
      genericIcon: GenericIcon.imageXGeneric,
      comments: [IntlString.constant('glTF model')],
      acronym: IntlString.constant('glTF'),
      expandedAcronym: IntlString.constant('GL Transmission Format'),
      subclassOf: ['application/json'],
      alias: [],
      globs: [Glob(pattern: '*.gltf', weight: 50, caseSensitive: false)],
    ),
  ],
  'model/vrml': [
    RegistryEntry(
      mediaType: 'model/vrml',
      genericIcon: GenericIcon.xOfficeDocument,
      comments: [IntlString.constant('VRML document')],
      acronym: IntlString.constant('VRML'),
      expandedAcronym: IntlString.constant('Virtual Reality Modeling Language'),
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: '*.vrm', weight: 50, caseSensitive: false),
        Glob(pattern: '*.vrml', weight: 50, caseSensitive: false),
        Glob(pattern: '*.wrl', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#VRML ',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'model/obj': [
    RegistryEntry(
      mediaType: 'model/obj',
      genericIcon: GenericIcon.imageXGeneric,
      comments: [IntlString.constant('OBJ 3D model')],
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.obj', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0:64',
              value: ' OBJ File: \'',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0:256',
              value: 'mtllib ',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'model/mtl': [
    RegistryEntry(
      mediaType: 'model/mtl',
      genericIcon: GenericIcon.imageXGeneric,
      comments: [IntlString.constant('OBJ 3D model material library')],
      subclassOf: ['text/plain'],
      alias: [],
      globs: [Glob(pattern: '*.mtl', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '# Blender MTL File: \'',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0:256',
              value: 'newmtl ',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'model/3mf': [
    RegistryEntry(
      mediaType: 'model/3mf',
      genericIcon: GenericIcon.imageXGeneric,
      comments: [IntlString.constant('3MF document')],
      acronym: IntlString.constant('3MF'),
      expandedAcronym: IntlString.constant('3D Manufacturing Format'),
      subclassOf: ['application/zip'],
      alias: ['application/vnd.ms-3mfdocument'],
      globs: [Glob(pattern: '*.3mf', weight: 50, caseSensitive: false)],
    ),
  ],
  'model/stl': [
    RegistryEntry(
      mediaType: 'model/stl',
      genericIcon: GenericIcon.imageXGeneric,
      comments: [IntlString.constant('STL 3D model')],
      acronym: IntlString.constant('STL'),
      expandedAcronym: IntlString.constant('StereoLithography'),
      subclassOf: [],
      alias: ['model/x.stl-ascii', 'model/x.stl-binary'],
      globs: [Glob(pattern: '*.stl', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'solid',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'SOLID',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
};
