// Copyright 2026 The Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Generated by tool/loader.dart
// ignore_for_file: non_constant_identifier_names,unused_import

import 'package:betto_mediatype_detector/betto_mediatype_detector.dart';
import 'package:betto_common/string.dart';
import 'package:meta/meta.dart';

@internal
final Registry mimeinfoDbChemical = {
  'chemical/x-pdb': [
    RegistryEntry(
      mediaType: 'chemical/x-pdb',
      genericIcon: GenericIcon.textXGeneric,
      comments: [IntlString.constant('Protein Data Bank file')],
      subclassOf: ['text/plain'],
      alias: [],
      globs: [
        Glob(pattern: '*.pdb', weight: 50, caseSensitive: false),
        Glob(pattern: '*.brk', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 40,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'HEADER ',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
};
