// Copyright 2026 The Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Generated by tool/loader.dart
// ignore_for_file: non_constant_identifier_names,unused_import

import 'package:betto_mediatype_detector/mediatype_detector.dart';
import 'package:betto_common/string.dart';
import 'package:meta/meta.dart';

@internal
final Registry mimeinfoDbMultipart = {
  'multipart/alternative': [
    RegistryEntry(
      mediaType: 'multipart/alternative',
      comments: [IntlString.constant('Message in several formats')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'multipart/appledouble': [
    RegistryEntry(
      mediaType: 'multipart/appledouble',
      comments: [IntlString.constant('Macintosh AppleDouble-encoded file')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'multipart/digest': [
    RegistryEntry(
      mediaType: 'multipart/digest',
      comments: [IntlString.constant('Message digest')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'multipart/encrypted': [
    RegistryEntry(
      mediaType: 'multipart/encrypted',
      comments: [IntlString.constant('Encrypted message')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'multipart/mixed': [
    RegistryEntry(
      mediaType: 'multipart/mixed',
      comments: [IntlString.constant('Compound documents')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'multipart/related': [
    RegistryEntry(
      mediaType: 'multipart/related',
      comments: [IntlString.constant('Compound document')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'multipart/report': [
    RegistryEntry(
      mediaType: 'multipart/report',
      comments: [IntlString.constant('Mail system report')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'multipart/signed': [
    RegistryEntry(
      mediaType: 'multipart/signed',
      comments: [IntlString.constant('Signed message')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'multipart/x-mixed-replace': [
    RegistryEntry(
      mediaType: 'multipart/x-mixed-replace',
      comments: [IntlString.constant('Stream of data (server push)')],
      subclassOf: [],
      alias: [],
    ),
  ],
};
