// Copyright 2026 The Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Generated by tool/loader.dart
// ignore_for_file: non_constant_identifier_names,unused_import

import 'package:betto_mediatype_detector/mediatype_detector.dart';
import 'package:betto_common/string.dart';
import 'package:meta/meta.dart';

@internal
final Registry mimeinfoDbVideo = {
  'video/x-flv': [
    RegistryEntry(
      mediaType: 'video/x-flv',
      genericIcon: GenericIcon.videoXGeneric,
      comments: [IntlString.constant('Flash video')],
      subclassOf: [],
      alias: [
        'application/x-flash-video',
        'flv-application/octet-stream',
        'video/flv',
      ],
      globs: [Glob(pattern: '*.flv', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'FLV',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/x-javafx': [
    RegistryEntry(
      mediaType: 'video/x-javafx',
      genericIcon: GenericIcon.videoXGeneric,
      comments: [IntlString.constant('JavaFX video')],
      subclassOf: ['video/x-flv'],
      alias: [],
      globs: [Glob(pattern: '*.fxm', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 40,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'FLV',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/vnd.youtube.yt': [
    RegistryEntry(
      mediaType: 'video/vnd.youtube.yt',
      genericIcon: GenericIcon.videoXGeneric,
      comments: [IntlString.constant('YouTube media archive')],
      subclassOf: ['application/zip'],
      alias: ['application/vnd.youtube.yt'],
      globs: [Glob(pattern: '*.yt', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftypyt4 ',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/x-matroska': [
    RegistryEntry(
      mediaType: 'video/x-matroska',
      comments: [IntlString.constant('Matroska video')],
      subclassOf: ['application/x-matroska'],
      alias: [],
      globs: [Glob(pattern: '*.mkv', weight: 50, caseSensitive: false)],
    ),
  ],
  'video/x-matroska-3d': [
    RegistryEntry(
      mediaType: 'video/x-matroska-3d',
      comments: [IntlString.constant('Matroska 3D video')],
      subclassOf: ['application/x-matroska'],
      alias: [],
      globs: [Glob(pattern: '*.mk3d', weight: 50, caseSensitive: false)],
    ),
  ],
  'video/webm': [
    RegistryEntry(
      mediaType: 'video/webm',
      comments: [IntlString.constant('WebM video')],
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.webm', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.big32,
              offset: '0',
              value: '0x1a45dfa3',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.big16,
                  offset: '5:65',
                  value: '0x4282',
                  mask: null,
                  minShouldMatch: null,
                  subMatches: [
                    Match.factory(
                      type: MatchType.string,
                      offset: '8:75',
                      value: 'webm',
                      mask: null,
                      minShouldMatch: null,
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'video/annodex': [
    RegistryEntry(
      mediaType: 'video/annodex',
      comments: [IntlString.constant('Annodex video')],
      subclassOf: ['application/annodex'],
      alias: ['video/x-annodex'],
      globs: [Glob(pattern: '*.axv', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'OggS',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '28',
                  value: 'fishead\x00',
                  mask: null,
                  minShouldMatch: null,
                  subMatches: [
                    Match.factory(
                      type: MatchType.string,
                      offset: '56:512',
                      value: 'CMML\x00\x00\x00\x00',
                      mask: null,
                      minShouldMatch: null,
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'video/ogg': [
    RegistryEntry(
      mediaType: 'video/ogg',
      comments: [IntlString.constant('Ogg video')],
      subclassOf: ['application/ogg'],
      alias: ['video/x-ogg'],
      globs: [
        Glob(pattern: '*.ogv', weight: 50, caseSensitive: false),
        Glob(pattern: '*.ogg', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'OggS',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/x-theora+ogg': [
    RegistryEntry(
      mediaType: 'video/x-theora+ogg',
      comments: [IntlString.constant('Ogg Theora video')],
      subclassOf: ['video/ogg'],
      alias: ['video/x-theora'],
      globs: [Glob(pattern: '*.ogg', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 80,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'OggS',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '28',
                  value: '\x80theora',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'video/x-ogm+ogg': [
    RegistryEntry(
      mediaType: 'video/x-ogm+ogg',
      comments: [IntlString.constant('OGM video')],
      subclassOf: ['video/ogg'],
      alias: ['video/x-ogm'],
      globs: [Glob(pattern: '*.ogm', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 80,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'OggS',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '29',
                  value: 'video',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'video/mp4': [
    RegistryEntry(
      mediaType: 'video/mp4',
      comments: [IntlString.constant('MPEG-4 video')],
      subclassOf: [],
      alias: ['video/mp4v-es', 'video/x-m4v'],
      globs: [
        Glob(pattern: '*.mp4', weight: 50, caseSensitive: false),
        Glob(pattern: '*.m4v', weight: 50, caseSensitive: false),
        Glob(pattern: '*.f4v', weight: 50, caseSensitive: false),
        Glob(pattern: '*.lrv', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftypisom',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftypmp41',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftypmp42',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftypMSNV',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftypM4V ',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftypf4v ',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/3gpp': [
    RegistryEntry(
      mediaType: 'video/3gpp',
      comments: [IntlString.constant('3GPP multimedia file')],
      acronym: IntlString.constant('3GPP'),
      expandedAcronym: IntlString.constant(
        '3rd Generation Partnership Project',
      ),
      subclassOf: ['video/mp4'],
      alias: [
        'video/3gp',
        'audio/3gpp',
        'video/3gpp-encrypted',
        'audio/3gpp-encrypted',
        'audio/x-rn-3gpp-amr',
        'audio/x-rn-3gpp-amr-encrypted',
        'audio/x-rn-3gpp-amr-wb',
        'audio/x-rn-3gpp-amr-wb-encrypted',
      ],
      globs: [
        Glob(pattern: '*.3gp', weight: 50, caseSensitive: false),
        Glob(pattern: '*.3gpp', weight: 50, caseSensitive: false),
        Glob(pattern: '*.3ga', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftyp3ge',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftyp3gg',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftyp3gp',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftyp3gs',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/3gpp2': [
    RegistryEntry(
      mediaType: 'video/3gpp2',
      comments: [IntlString.constant('3GPP2 multimedia file')],
      acronym: IntlString.constant('3GPP2'),
      expandedAcronym: IntlString.constant(
        '3rd Generation Partnership Project 2',
      ),
      subclassOf: [],
      alias: ['audio/3gpp2'],
      globs: [
        Glob(pattern: '*.3g2', weight: 50, caseSensitive: false),
        Glob(pattern: '*.3gp2', weight: 50, caseSensitive: false),
        Glob(pattern: '*.3gpp2', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftyp3g2',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/vnd.rn-realvideo': [
    RegistryEntry(
      mediaType: 'video/vnd.rn-realvideo',
      comments: [IntlString.constant('RealVideo document')],
      subclassOf: [],
      alias: ['video/x-real-video'],
      globs: [
        Glob(pattern: '*.rv', weight: 50, caseSensitive: false),
        Glob(pattern: '*.rvx', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'video/x-mjpeg': [
    RegistryEntry(
      mediaType: 'video/x-mjpeg',
      comments: [IntlString.constant('MJPEG video stream')],
      acronym: IntlString.constant('MJPEG'),
      expandedAcronym: IntlString.constant('Motion JPEG'),
      subclassOf: ['image/jpeg'],
      alias: [],
      globs: [
        Glob(pattern: '*.mjpeg', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mjpg', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'video/mj2': [
    RegistryEntry(
      mediaType: 'video/mj2',
      comments: [IntlString.constant('JPEG-2000 MJ2 video')],
      acronym: IntlString.constant('MJ2'),
      expandedAcronym: IntlString.constant('Motion JPEG-2000'),
      subclassOf: [],
      alias: [],
      globs: [
        Glob(pattern: '*.mj2', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mjp2', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '\x00\x00\x00\fjP  \r\n\x87\n        mjp2',
              mask: '0xffffffffffffffffffffffff0000000000000000ffffffff',
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/dv': [
    RegistryEntry(
      mediaType: 'video/dv',
      comments: [IntlString.constant('DV video')],
      acronym: IntlString.constant('DV'),
      expandedAcronym: IntlString.constant('Digital Video'),
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.dv', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.big32,
              offset: '0',
              value: '0x1f070000',
              mask: '0xffffff00',
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/isivideo': [
    RegistryEntry(
      mediaType: 'video/isivideo',
      comments: [IntlString.constant('ISI video')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'video/mp2t': [
    RegistryEntry(
      mediaType: 'video/mp2t',
      comments: [IntlString.constant('MPEG-2 transport stream')],
      acronym: IntlString.constant('MPEG-2 TS'),
      expandedAcronym: IntlString.constant(
        'Moving Picture Experts Group 2 Transport Stream',
      ),
      subclassOf: [],
      alias: [],
      globs: [
        Glob(pattern: '*.m2t', weight: 50, caseSensitive: false),
        Glob(pattern: '*.m2ts', weight: 50, caseSensitive: false),
        Glob(pattern: '*.ts', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mts', weight: 50, caseSensitive: false),
        Glob(pattern: '*.cpi', weight: 50, caseSensitive: false),
        Glob(pattern: '*.clpi', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mpl', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mpls', weight: 50, caseSensitive: false),
        Glob(pattern: '*.bdm', weight: 50, caseSensitive: false),
        Glob(pattern: '*.bdmv', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.byte,
              offset: '0',
              value: '0x47',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.byte,
                  offset: '188',
                  value: '0x47',
                  mask: null,
                  minShouldMatch: null,
                  subMatches: [
                    Match.factory(
                      type: MatchType.byte,
                      offset: '376',
                      value: '0x47',
                      mask: null,
                      minShouldMatch: null,
                      subMatches: [
                        Match.factory(
                          type: MatchType.byte,
                          offset: '564',
                          value: '0x47',
                          mask: null,
                          minShouldMatch: null,
                          subMatches: [
                            Match.factory(
                              type: MatchType.byte,
                              offset: '752',
                              value: '0x47',
                              mask: null,
                              minShouldMatch: null,
                            ),
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
            Match.factory(
              type: MatchType.byte,
              offset: '4',
              value: '0x47',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.byte,
                  offset: '196',
                  value: '0x47',
                  mask: null,
                  minShouldMatch: null,
                  subMatches: [
                    Match.factory(
                      type: MatchType.byte,
                      offset: '388',
                      value: '0x47',
                      mask: null,
                      minShouldMatch: null,
                      subMatches: [
                        Match.factory(
                          type: MatchType.byte,
                          offset: '580',
                          value: '0x47',
                          mask: null,
                          minShouldMatch: null,
                          subMatches: [
                            Match.factory(
                              type: MatchType.byte,
                              offset: '772',
                              value: '0x47',
                              mask: null,
                              minShouldMatch: null,
                            ),
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'video/mpeg': [
    RegistryEntry(
      mediaType: 'video/mpeg',
      comments: [IntlString.constant('MPEG video')],
      acronym: IntlString.constant('MPEG'),
      expandedAcronym: IntlString.constant('Moving Picture Experts Group'),
      subclassOf: [],
      alias: [
        'video/x-mpeg',
        'video/mpeg-system',
        'video/x-mpeg-system',
        'video/x-mpeg2',
      ],
      globs: [
        Glob(pattern: '*.mpeg', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mpg', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mp2', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mpe', weight: 50, caseSensitive: false),
        Glob(pattern: '*.vob', weight: 50, caseSensitive: false),
        Glob(pattern: '[0-9][0-9][0-9].vdr', weight: 50, caseSensitive: true),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'G?\xff\x10',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.big32,
              offset: '0',
              value: '0x000001b3',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.big32,
              offset: '0',
              value: '0x000001ba',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/vnd.mpegurl': [
    RegistryEntry(
      mediaType: 'video/vnd.mpegurl',
      comments: [IntlString.constant('Video playlist')],
      subclassOf: ['text/plain'],
      alias: ['video/x-mpegurl'],
      globs: [
        Glob(pattern: '*.m1u', weight: 50, caseSensitive: false),
        Glob(pattern: '*.m4u', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mxu', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '#EXTM4U',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/quicktime': [
    RegistryEntry(
      mediaType: 'video/quicktime',
      comments: [IntlString.constant('QuickTime video')],
      subclassOf: [],
      alias: [],
      globs: [
        Glob(pattern: '*.qt', weight: 50, caseSensitive: false),
        Glob(pattern: '*.mov', weight: 50, caseSensitive: false),
        Glob(pattern: '*.moov', weight: 50, caseSensitive: false),
        Glob(pattern: '*.qtvr', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '12',
              value: 'mdat',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'mdat',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'moov',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.string,
              offset: '4',
              value: 'ftypqt',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/vnd.vivo': [
    RegistryEntry(
      mediaType: 'video/vnd.vivo',
      comments: [IntlString.constant('Vivo video')],
      subclassOf: [],
      alias: ['video/vivo'],
      globs: [
        Glob(pattern: '*.viv', weight: 50, caseSensitive: false),
        Glob(pattern: '*.vivo', weight: 50, caseSensitive: false),
      ],
    ),
  ],
  'video/wavelet': [
    RegistryEntry(
      mediaType: 'video/wavelet',
      comments: [IntlString.constant('Wavelet video')],
      subclassOf: [],
      alias: [],
    ),
  ],
  'video/x-anim': [
    RegistryEntry(
      mediaType: 'video/x-anim',
      comments: [IntlString.constant('ANIM animation')],
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.anim[1-9j]', weight: 50, caseSensitive: true)],
    ),
  ],
  'video/x-flic': [
    RegistryEntry(
      mediaType: 'video/x-flic',
      comments: [IntlString.constant('FLIC animation')],
      subclassOf: [],
      alias: ['video/fli', 'video/x-fli'],
      globs: [
        Glob(pattern: '*.fli', weight: 50, caseSensitive: false),
        Glob(pattern: '*.flc', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.little16,
              offset: '0',
              value: '0xAF11',
              mask: null,
              minShouldMatch: null,
            ),
            Match.factory(
              type: MatchType.little16,
              offset: '0',
              value: '0xAF12',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/x-mng': [
    RegistryEntry(
      mediaType: 'video/x-mng',
      comments: [IntlString.constant('MNG animation')],
      acronym: IntlString.constant('MNG'),
      expandedAcronym: IntlString.constant('Multiple-Image Network Graphics'),
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.mng', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: '\x8aMNG\r\n\x1a\n',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/x-ms-wmv': [
    RegistryEntry(
      mediaType: 'video/x-ms-wmv',
      comments: [IntlString.constant('Windows Media video')],
      subclassOf: ['application/vnd.ms-asf'],
      alias: [],
      globs: [Glob(pattern: '*.wmv', weight: 50, caseSensitive: false)],
    ),
  ],
  'video/vnd.avi': [
    RegistryEntry(
      mediaType: 'video/vnd.avi',
      comments: [IntlString.constant('AVI video')],
      acronym: IntlString.constant('AVI'),
      expandedAcronym: IntlString.constant('Audio Video Interleave'),
      subclassOf: [],
      alias: [
        'video/x-avi',
        'video/avi',
        'video/divx',
        'video/msvideo',
        'video/vnd.divx',
        'video/x-msvideo',
      ],
      globs: [
        Glob(pattern: '*.avi', weight: 50, caseSensitive: false),
        Glob(pattern: '*.avf', weight: 50, caseSensitive: false),
        Glob(pattern: '*.divx', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'RIFF',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '8',
                  value: 'AVI ',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'AVF0',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '8',
                  value: 'AVI ',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'video/x-nsv': [
    RegistryEntry(
      mediaType: 'video/x-nsv',
      comments: [IntlString.constant('NullSoft video')],
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.nsv', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'NSVf',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/x-sgi-movie': [
    RegistryEntry(
      mediaType: 'video/x-sgi-movie',
      comments: [IntlString.constant('SGI video')],
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.movie', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'MOVI',
              mask: null,
              minShouldMatch: null,
            ),
          ],
        ),
      ],
    ),
  ],
  'video/vnd.radgamettools.bink': [
    RegistryEntry(
      mediaType: 'video/vnd.radgamettools.bink',
      comments: [IntlString.constant('Bink Video')],
      subclassOf: [],
      alias: [],
      globs: [
        Glob(pattern: '*.bik', weight: 50, caseSensitive: false),
        Glob(pattern: '*.bk2', weight: 50, caseSensitive: false),
      ],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'BIK',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: 'b',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: 'f',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: 'g',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: 'h',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: 'i',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'KB2',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: 'a',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: 'd',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: 'f',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: 'g',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: 'h',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: 'i',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: 'j',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: 'k',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
  'video/vnd.radgamettools.smacker': [
    RegistryEntry(
      mediaType: 'video/vnd.radgamettools.smacker',
      comments: [IntlString.constant('Smacker Video')],
      subclassOf: [],
      alias: [],
      globs: [Glob(pattern: '*.smk', weight: 50, caseSensitive: false)],
      magic: [
        Magic(
          priority: 50,
          matches: [
            Match.factory(
              type: MatchType.string,
              offset: '0',
              value: 'SMK',
              mask: null,
              minShouldMatch: null,
              subMatches: [
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: '2',
                  mask: null,
                  minShouldMatch: null,
                ),
                Match.factory(
                  type: MatchType.string,
                  offset: '3',
                  value: '4',
                  mask: null,
                  minShouldMatch: null,
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  ],
};
